-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity scatter_matrix_sin_or_cos_float_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    t_in : IN STD_LOGIC_VECTOR (31 downto 0);
    do_cos : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of scatter_matrix_sin_or_cos_float_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_C2 : STD_LOGIC_VECTOR (7 downto 0) := "11000010";
    constant ap_const_lv8_3F : STD_LOGIC_VECTOR (7 downto 0) := "00111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv8_83 : STD_LOGIC_VECTOR (7 downto 0) := "10000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv58_0 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv29_1FFFFFFF : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111111111111111";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv19_40000 : STD_LOGIC_VECTOR (18 downto 0) := "1000000000000000000";
    constant ap_const_lv9_7F : STD_LOGIC_VECTOR (8 downto 0) := "001111111";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv23_7FFFFF : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111111111";

attribute shreg_extract : string;
    signal ref_4oPi_table_100_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ref_4oPi_table_100_q0 : STD_LOGIC_VECTOR (99 downto 0);
    signal second_order_float_sin_cos_K0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K0_q0 : STD_LOGIC_VECTOR (29 downto 0);
    signal second_order_float_sin_cos_K1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K1_q0 : STD_LOGIC_VECTOR (22 downto 0);
    signal second_order_float_sin_cos_K2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K2_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal do_cos_read_reg_1257 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal do_cos_read_reg_1257_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1257_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1257_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1257_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1257_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1257_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1257_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1257_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1265 : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1265_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1265_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1265_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_exp_fu_308_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1271 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1271_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1271_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1271_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_sig_fu_318_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal din_sig_reg_1278 : STD_LOGIC_VECTOR (22 downto 0);
    signal din_sig_reg_1278_pp0_iter1_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal closepath_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1284 : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1284_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1284_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1284_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln379_fu_357_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln379_reg_1295 : STD_LOGIC_VECTOR (3 downto 0);
    signal Med_reg_1300 : STD_LOGIC_VECTOR (79 downto 0);
    signal icmp_ln271_1_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1310 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1310_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_bits_reg_1315 : STD_LOGIC_VECTOR (57 downto 0);
    signal k_reg_1321 : STD_LOGIC_VECTOR (2 downto 0);
    signal Mx_reg_1326 : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_reg_1326_pp0_iter5_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_reg_1326_pp0_iter6_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_reg_1326_pp0_iter7_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal Ex_1_fu_527_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_1_reg_1332 : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_1_reg_1332_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_1_reg_1332_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_1_reg_1332_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_1_reg_1332_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_1338 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln506_fu_541_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln506_reg_1344 : STD_LOGIC_VECTOR (7 downto 0);
    signal cos_basis_fu_593_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cos_basis_reg_1349 : STD_LOGIC_VECTOR (0 downto 0);
    signal cos_basis_reg_1349_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cos_basis_reg_1349_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cos_basis_reg_1349_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cos_basis_reg_1349_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sin_basis_fu_600_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sin_basis_reg_1355 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1360 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1360_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1360_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1360_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1360_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_fu_786_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1366 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1366_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1366_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1366_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1366_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_fu_803_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1373 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1373_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1373_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1373_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1373_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal B_fu_842_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal B_reg_1378 : STD_LOGIC_VECTOR (21 downto 0);
    signal B_squared_reg_1383 : STD_LOGIC_VECTOR (14 downto 0);
    signal t1_reg_1403 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln_reg_1408 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln1_reg_1413 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln32_1_fu_967_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln32_1_reg_1418 : STD_LOGIC_VECTOR (29 downto 0);
    signal result_reg_1423 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_8_reg_1429 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_reg_1434 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln378_fu_352_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln28_fu_893_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ref_4oPi_table_100_ce0_local : STD_LOGIC;
    signal second_order_float_sin_cos_K0_ce0_local : STD_LOGIC;
    signal second_order_float_sin_cos_K1_ce0_local : STD_LOGIC;
    signal second_order_float_sin_cos_K2_ce0_local : STD_LOGIC;
    signal mul_ln29_fu_284_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal mul_ln32_fu_288_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_292_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal data_fu_296_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln376_fu_328_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal addr_fu_334_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln_fu_342_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln379_fu_361_p1 : STD_LOGIC_VECTOR (99 downto 0);
    signal shl_ln379_fu_364_p2 : STD_LOGIC_VECTOR (99 downto 0);
    signal X_fu_380_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_292_p2 : STD_LOGIC_VECTOR (79 downto 0);
    signal Ex_fu_417_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_1_fu_429_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln491_fu_435_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_bits_1_fu_439_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal Mx_bits_2_fu_444_p3 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_s_fu_451_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal t_fu_461_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_3_fu_469_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_4_fu_479_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln75_fu_487_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_491_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal Mx_zeros_fu_499_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln504_fu_503_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal shl_ln504_fu_507_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal select_ln453_fu_422_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln505_fu_523_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_547_p17 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_547_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln242_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_614_p33 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_fu_607_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p33 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_614_p35 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_686_p35 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_fu_766_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln278_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_fu_758_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln282_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_2_fu_781_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_4_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln506_fu_811_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln506_fu_820_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln506_1_fu_816_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln506_fu_823_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln506_fu_829_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln506_1_fu_835_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_trunc_fu_856_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln23_fu_870_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln23_fu_866_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln23_fu_870_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln23_fu_870_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_7_fu_846_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal A_fu_886_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln29_fu_284_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln30_fu_936_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln30_fu_936_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln32_fu_952_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln32_1_fu_955_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln32_fu_958_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln32_2_fu_964_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal Mx_1_fu_973_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln32_fu_288_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal Ex_2_fu_1018_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_bits_fu_1028_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_1042_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_bits_2_fu_1035_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_1060_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln291_fu_1078_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_fu_1052_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln291_fu_1081_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_fu_1070_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_shift_1_fu_1087_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln291_1_fu_1103_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln292_fu_1091_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shift_1_fu_1097_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln252_fu_1024_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln300_fu_1121_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln300_fu_1127_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shift_2_fu_1113_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newexp_fu_1131_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_1137_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln306_fu_1145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln291_1_fu_1107_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_1160_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_12_fu_1170_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln306_fu_1150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln282_fu_1202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln282_fu_1195_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_1156_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln282_2_fu_1215_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal empty_35_fu_1180_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal select_ln259_fu_1188_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal results_exp_fu_1207_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal results_sig_fu_1222_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal results_exp_1_fu_1230_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal results_sig_1_fu_1237_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal t_2_fu_1244_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_292_ce : STD_LOGIC;
    signal t_in_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal do_cos_int_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_292_p10 : STD_LOGIC_VECTOR (79 downto 0);
    signal mul_ln29_fu_284_p10 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln30_fu_936_p00 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln32_fu_288_p10 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_6_fu_547_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_547_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_547_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_547_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_547_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_547_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_547_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_547_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_13_fu_614_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_13_fu_614_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_14_fu_686_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component scatter_matrix_mul_23s_22ns_45_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        dout : OUT STD_LOGIC_VECTOR (44 downto 0) );
    end component;


    component scatter_matrix_mul_30s_29ns_58_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (29 downto 0);
        din1 : IN STD_LOGIC_VECTOR (28 downto 0);
        dout : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component scatter_matrix_mul_80s_24ns_80_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (79 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (79 downto 0) );
    end component;


    component scatter_matrix_sparsemux_17_3_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component scatter_matrix_sparsemux_33_4_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (0 downto 0);
        din9 : IN STD_LOGIC_VECTOR (0 downto 0);
        din10 : IN STD_LOGIC_VECTOR (0 downto 0);
        din11 : IN STD_LOGIC_VECTOR (0 downto 0);
        din12 : IN STD_LOGIC_VECTOR (0 downto 0);
        din13 : IN STD_LOGIC_VECTOR (0 downto 0);
        din14 : IN STD_LOGIC_VECTOR (0 downto 0);
        din15 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component scatter_matrix_mul_15ns_15ns_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component scatter_matrix_mul_15ns_15s_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component scatter_matrix_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (99 downto 0) );
    end component;


    component scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;



begin
    ref_4oPi_table_100_U : component scatter_matrix_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 100,
        AddressRange => 13,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ref_4oPi_table_100_address0,
        ce0 => ref_4oPi_table_100_ce0_local,
        q0 => ref_4oPi_table_100_q0);

    second_order_float_sin_cos_K0_U : component scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 30,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K0_address0,
        ce0 => second_order_float_sin_cos_K0_ce0_local,
        q0 => second_order_float_sin_cos_K0_q0);

    second_order_float_sin_cos_K1_U : component scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 23,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K1_address0,
        ce0 => second_order_float_sin_cos_K1_ce0_local,
        q0 => second_order_float_sin_cos_K1_q0);

    second_order_float_sin_cos_K2_U : component scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 15,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K2_address0,
        ce0 => second_order_float_sin_cos_K2_ce0_local,
        q0 => second_order_float_sin_cos_K2_q0);

    mul_23s_22ns_45_1_1_U21 : component scatter_matrix_mul_23s_22ns_45_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 23,
        din1_WIDTH => 22,
        dout_WIDTH => 45)
    port map (
        din0 => second_order_float_sin_cos_K1_q0,
        din1 => mul_ln29_fu_284_p1,
        dout => mul_ln29_fu_284_p2);

    mul_30s_29ns_58_1_1_U22 : component scatter_matrix_mul_30s_29ns_58_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 30,
        din1_WIDTH => 29,
        dout_WIDTH => 58)
    port map (
        din0 => add_ln32_1_reg_1418,
        din1 => mul_ln32_fu_288_p1,
        dout => mul_ln32_fu_288_p2);

    mul_80s_24ns_80_2_1_U23 : component scatter_matrix_mul_80s_24ns_80_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 80,
        din1_WIDTH => 24,
        dout_WIDTH => 80)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Med_reg_1300,
        din1 => grp_fu_292_p1,
        ce => grp_fu_292_ce,
        dout => grp_fu_292_p2);

    sparsemux_17_3_1_1_1_U24 : component scatter_matrix_sparsemux_17_3_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 1,
        CASE1 => "001",
        din1_WIDTH => 1,
        CASE2 => "010",
        din2_WIDTH => 1,
        CASE3 => "011",
        din3_WIDTH => 1,
        CASE4 => "100",
        din4_WIDTH => 1,
        CASE5 => "101",
        din5_WIDTH => 1,
        CASE6 => "110",
        din6_WIDTH => 1,
        CASE7 => "111",
        din7_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 3,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_1,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => ap_const_lv1_0,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_1,
        din7 => ap_const_lv1_0,
        def => tmp_6_fu_547_p17,
        sel => k_1_fu_429_p3,
        dout => tmp_6_fu_547_p19);

    sparsemux_33_4_1_1_1_U25 : component scatter_matrix_sparsemux_33_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        CASE9 => "1001",
        din9_WIDTH => 1,
        CASE10 => "1010",
        din10_WIDTH => 1,
        CASE11 => "1011",
        din11_WIDTH => 1,
        CASE12 => "1100",
        din12_WIDTH => 1,
        CASE13 => "1101",
        din13_WIDTH => 1,
        CASE14 => "1110",
        din14_WIDTH => 1,
        CASE15 => "1111",
        din15_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_1,
        din4 => ap_const_lv1_1,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_1,
        din7 => ap_const_lv1_0,
        din8 => ap_const_lv1_0,
        din9 => ap_const_lv1_1,
        din10 => ap_const_lv1_1,
        din11 => ap_const_lv1_1,
        din12 => ap_const_lv1_1,
        din13 => ap_const_lv1_0,
        din14 => ap_const_lv1_0,
        din15 => ap_const_lv1_0,
        def => tmp_13_fu_614_p33,
        sel => index_fu_607_p3,
        dout => tmp_13_fu_614_p35);

    sparsemux_33_4_1_1_1_U26 : component scatter_matrix_sparsemux_33_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        CASE9 => "1001",
        din9_WIDTH => 1,
        CASE10 => "1010",
        din10_WIDTH => 1,
        CASE11 => "1011",
        din11_WIDTH => 1,
        CASE12 => "1100",
        din12_WIDTH => 1,
        CASE13 => "1101",
        din13_WIDTH => 1,
        CASE14 => "1110",
        din14_WIDTH => 1,
        CASE15 => "1111",
        din15_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => ap_const_lv1_1,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_0,
        din7 => ap_const_lv1_1,
        din8 => ap_const_lv1_1,
        din9 => ap_const_lv1_0,
        din10 => ap_const_lv1_1,
        din11 => ap_const_lv1_1,
        din12 => ap_const_lv1_0,
        din13 => ap_const_lv1_1,
        din14 => ap_const_lv1_0,
        din15 => ap_const_lv1_0,
        def => tmp_14_fu_686_p33,
        sel => index_fu_607_p3,
        dout => tmp_14_fu_686_p35);

    mul_15ns_15ns_30_1_1_U27 : component scatter_matrix_mul_15ns_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln23_fu_870_p0,
        din1 => mul_ln23_fu_870_p1,
        dout => mul_ln23_fu_870_p2);

    mul_15ns_15s_30_1_1_U28 : component scatter_matrix_mul_15ns_15s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln30_fu_936_p0,
        din1 => second_order_float_sin_cos_K2_q0,
        dout => mul_ln30_fu_936_p2);




    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                B_reg_1378 <= B_fu_842_p1;
                B_squared_reg_1383 <= mul_ln23_fu_870_p2(29 downto 15);
                Ex_1_reg_1332 <= Ex_1_fu_527_p2;
                Ex_1_reg_1332_pp0_iter5_reg <= Ex_1_reg_1332;
                Ex_1_reg_1332_pp0_iter6_reg <= Ex_1_reg_1332_pp0_iter5_reg;
                Ex_1_reg_1332_pp0_iter7_reg <= Ex_1_reg_1332_pp0_iter6_reg;
                Ex_1_reg_1332_pp0_iter8_reg <= Ex_1_reg_1332_pp0_iter7_reg;
                Med_reg_1300 <= shl_ln379_fu_364_p2(99 downto 20);
                Mx_bits_reg_1315 <= grp_fu_292_p2(76 downto 19);
                Mx_reg_1326 <= shl_ln504_fu_507_p2(57 downto 29);
                Mx_reg_1326_pp0_iter5_reg <= Mx_reg_1326;
                Mx_reg_1326_pp0_iter6_reg <= Mx_reg_1326_pp0_iter5_reg;
                Mx_reg_1326_pp0_iter7_reg <= Mx_reg_1326_pp0_iter6_reg;
                add_ln32_1_reg_1418 <= add_ln32_1_fu_967_p2;
                and_ln271_reg_1360 <= and_ln271_fu_771_p2;
                and_ln271_reg_1360_pp0_iter5_reg <= and_ln271_reg_1360;
                and_ln271_reg_1360_pp0_iter6_reg <= and_ln271_reg_1360_pp0_iter5_reg;
                and_ln271_reg_1360_pp0_iter7_reg <= and_ln271_reg_1360_pp0_iter6_reg;
                and_ln271_reg_1360_pp0_iter8_reg <= and_ln271_reg_1360_pp0_iter7_reg;
                closepath_reg_1284 <= closepath_fu_322_p2;
                closepath_reg_1284_pp0_iter1_reg <= closepath_reg_1284;
                closepath_reg_1284_pp0_iter2_reg <= closepath_reg_1284_pp0_iter1_reg;
                closepath_reg_1284_pp0_iter3_reg <= closepath_reg_1284_pp0_iter2_reg;
                cos_basis_reg_1349 <= cos_basis_fu_593_p3;
                cos_basis_reg_1349_pp0_iter5_reg <= cos_basis_reg_1349;
                cos_basis_reg_1349_pp0_iter6_reg <= cos_basis_reg_1349_pp0_iter5_reg;
                cos_basis_reg_1349_pp0_iter7_reg <= cos_basis_reg_1349_pp0_iter6_reg;
                cos_basis_reg_1349_pp0_iter8_reg <= cos_basis_reg_1349_pp0_iter7_reg;
                din_exp_reg_1271 <= data_fu_296_p1(30 downto 23);
                din_exp_reg_1271_pp0_iter1_reg <= din_exp_reg_1271;
                din_exp_reg_1271_pp0_iter2_reg <= din_exp_reg_1271_pp0_iter1_reg;
                din_exp_reg_1271_pp0_iter3_reg <= din_exp_reg_1271_pp0_iter2_reg;
                din_sig_reg_1278 <= din_sig_fu_318_p1;
                din_sig_reg_1278_pp0_iter1_reg <= din_sig_reg_1278;
                din_sign_reg_1265 <= data_fu_296_p1(31 downto 31);
                din_sign_reg_1265_pp0_iter1_reg <= din_sign_reg_1265;
                din_sign_reg_1265_pp0_iter2_reg <= din_sign_reg_1265_pp0_iter1_reg;
                din_sign_reg_1265_pp0_iter3_reg <= din_sign_reg_1265_pp0_iter2_reg;
                do_cos_read_reg_1257 <= do_cos_int_reg;
                do_cos_read_reg_1257_pp0_iter1_reg <= do_cos_read_reg_1257;
                do_cos_read_reg_1257_pp0_iter2_reg <= do_cos_read_reg_1257_pp0_iter1_reg;
                do_cos_read_reg_1257_pp0_iter3_reg <= do_cos_read_reg_1257_pp0_iter2_reg;
                do_cos_read_reg_1257_pp0_iter4_reg <= do_cos_read_reg_1257_pp0_iter3_reg;
                do_cos_read_reg_1257_pp0_iter5_reg <= do_cos_read_reg_1257_pp0_iter4_reg;
                do_cos_read_reg_1257_pp0_iter6_reg <= do_cos_read_reg_1257_pp0_iter5_reg;
                do_cos_read_reg_1257_pp0_iter7_reg <= do_cos_read_reg_1257_pp0_iter6_reg;
                do_cos_read_reg_1257_pp0_iter8_reg <= do_cos_read_reg_1257_pp0_iter7_reg;
                icmp_ln271_1_reg_1310 <= icmp_ln271_1_fu_392_p2;
                icmp_ln271_1_reg_1310_pp0_iter3_reg <= icmp_ln271_1_reg_1310;
                icmp_ln282_reg_1366 <= icmp_ln282_fu_786_p2;
                icmp_ln282_reg_1366_pp0_iter5_reg <= icmp_ln282_reg_1366;
                icmp_ln282_reg_1366_pp0_iter6_reg <= icmp_ln282_reg_1366_pp0_iter5_reg;
                icmp_ln282_reg_1366_pp0_iter7_reg <= icmp_ln282_reg_1366_pp0_iter6_reg;
                icmp_ln282_reg_1366_pp0_iter8_reg <= icmp_ln282_reg_1366_pp0_iter7_reg;
                k_reg_1321 <= grp_fu_292_p2(79 downto 77);
                result_reg_1423 <= mul_ln32_fu_288_p2(57 downto 29);
                results_sign_3_reg_1373 <= results_sign_3_fu_803_p3;
                results_sign_3_reg_1373_pp0_iter5_reg <= results_sign_3_reg_1373;
                results_sign_3_reg_1373_pp0_iter6_reg <= results_sign_3_reg_1373_pp0_iter5_reg;
                results_sign_3_reg_1373_pp0_iter7_reg <= results_sign_3_reg_1373_pp0_iter6_reg;
                results_sign_3_reg_1373_pp0_iter8_reg <= results_sign_3_reg_1373_pp0_iter7_reg;
                sin_basis_reg_1355 <= sin_basis_fu_600_p3;
                sub_ln506_reg_1344 <= sub_ln506_fu_541_p2;
                t1_reg_1403 <= second_order_float_sin_cos_K0_q0(29 downto 1);
                tmp_8_reg_1429 <= mul_ln32_fu_288_p2(57 downto 42);
                tmp_9_reg_1434 <= mul_ln32_fu_288_p2(41 downto 29);
                tmp_reg_1338 <= Ex_1_fu_527_p2(7 downto 7);
                trunc_ln1_reg_1413 <= mul_ln30_fu_936_p2(29 downto 16);
                trunc_ln379_reg_1295 <= trunc_ln379_fu_357_p1;
                trunc_ln_reg_1408 <= mul_ln29_fu_284_p2(44 downto 23);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                do_cos_int_reg <= do_cos;
                t_in_int_reg <= t_in;
            end if;
        end if;
    end process;
    A_fu_886_p3 <= (sin_basis_reg_1355 & tmp_7_fu_846_p4);
    B_fu_842_p1 <= select_ln506_1_fu_835_p3(22 - 1 downto 0);
    B_trunc_fu_856_p4 <= select_ln506_1_fu_835_p3(21 downto 7);
    Ex_1_fu_527_p2 <= std_logic_vector(unsigned(select_ln453_fu_422_p3) - unsigned(zext_ln505_fu_523_p1));
    Ex_2_fu_1018_p3 <= 
        ap_const_lv8_0 when (cos_basis_reg_1349_pp0_iter8_reg(0) = '1') else 
        Ex_1_reg_1332_pp0_iter8_reg;
    Ex_fu_417_p2 <= std_logic_vector(unsigned(din_exp_reg_1271_pp0_iter3_reg) + unsigned(ap_const_lv8_83));
    Mx_1_fu_973_p3 <= 
        ap_const_lv29_1FFFFFFF when (cos_basis_reg_1349_pp0_iter7_reg(0) = '1') else 
        Mx_reg_1326_pp0_iter7_reg;
    Mx_bits_1_fu_439_p2 <= std_logic_vector(unsigned(ap_const_lv58_0) - unsigned(Mx_bits_reg_1315));
    Mx_bits_2_fu_444_p3 <= 
        Mx_bits_1_fu_439_p2 when (trunc_ln491_fu_435_p1(0) = '1') else 
        Mx_bits_reg_1315;
    Mx_zeros_fu_499_p1 <= tmp_5_fu_491_p3(6 - 1 downto 0);
    X_fu_380_p3 <= (ap_const_lv1_1 & din_sig_reg_1278_pp0_iter1_reg);
    add_ln300_fu_1121_p2 <= std_logic_vector(signed(sext_ln252_fu_1024_p1) + signed(ap_const_lv9_7F));
    add_ln32_1_fu_967_p2 <= std_logic_vector(unsigned(add_ln32_fu_958_p2) + unsigned(sext_ln32_2_fu_964_p1));
    add_ln32_fu_958_p2 <= std_logic_vector(signed(sext_ln32_fu_952_p1) + signed(sext_ln32_1_fu_955_p1));
    add_ln376_fu_328_p2 <= std_logic_vector(unsigned(din_exp_fu_308_p4) + unsigned(ap_const_lv8_C2));
    addr_fu_334_p3 <= 
        ap_const_lv8_3F when (closepath_fu_322_p2(0) = '1') else 
        add_ln376_fu_328_p2;
    and_ln271_fu_771_p2 <= (icmp_ln271_fu_766_p2 and icmp_ln271_1_reg_1310_pp0_iter3_reg);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= t_2_fu_1244_p4;
    
    c_1_fu_1070_p3_proc : process(tmp_2_fu_1060_p4)
    begin
        c_1_fu_1070_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if tmp_2_fu_1060_p4(i) = '1' then
                c_1_fu_1070_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    
    c_fu_1052_p3_proc : process(tmp_1_fu_1042_p4)
    begin
        c_fu_1052_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if tmp_1_fu_1042_p4(i) = '1' then
                c_fu_1052_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    closepath_fu_322_p2 <= "1" when (unsigned(din_exp_fu_308_p4) < unsigned(ap_const_lv8_7E)) else "0";
    cos_basis_fu_593_p3 <= 
        xor_ln242_fu_587_p2 when (do_cos_read_reg_1257_pp0_iter3_reg(0) = '1') else 
        tmp_6_fu_547_p19;
    data_fu_296_p1 <= t_in_int_reg;
    din_exp_fu_308_p4 <= data_fu_296_p1(30 downto 23);
    din_sig_fu_318_p1 <= data_fu_296_p1(23 - 1 downto 0);
    empty_35_fu_1180_p3 <= 
        tmp_11_fu_1160_p4 when (icmp_ln292_fu_1091_p2(0) = '1') else 
        tmp_12_fu_1170_p4;
    empty_fu_1156_p1 <= newexp_fu_1131_p2(8 - 1 downto 0);

    grp_fu_292_ce_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            grp_fu_292_ce <= ap_const_logic_1;
        else 
            grp_fu_292_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_292_p1 <= grp_fu_292_p10(24 - 1 downto 0);
    grp_fu_292_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_fu_380_p3),80));
    icmp_ln271_1_fu_392_p2 <= "1" when (din_sig_reg_1278_pp0_iter1_reg = ap_const_lv23_0) else "0";
    icmp_ln271_fu_766_p2 <= "1" when (din_exp_reg_1271_pp0_iter3_reg = ap_const_lv8_0) else "0";
    icmp_ln282_fu_786_p2 <= "1" when (din_exp_reg_1271_pp0_iter3_reg = ap_const_lv8_FF) else "0";
    icmp_ln292_fu_1091_p2 <= "1" when (c_fu_1052_p3 = ap_const_lv32_10) else "0";
    icmp_ln306_fu_1145_p2 <= "1" when (result_reg_1423 = ap_const_lv29_0) else "0";
    in_shift_1_fu_1087_p1 <= shl_ln291_fu_1081_p2(28 - 1 downto 0);
    index_fu_607_p3 <= (din_sign_reg_1265_pp0_iter3_reg & k_1_fu_429_p3);
    k_1_fu_429_p3 <= 
        ap_const_lv3_0 when (closepath_reg_1284_pp0_iter3_reg(0) = '1') else 
        k_reg_1321;
    lshr_ln506_fu_823_p2 <= std_logic_vector(shift_right(unsigned(zext_ln506_fu_820_p1),to_integer(unsigned('0' & zext_ln506_1_fu_816_p1(31-1 downto 0)))));
    lshr_ln_fu_342_p4 <= addr_fu_334_p3(7 downto 4);
    mul_ln23_fu_870_p0 <= zext_ln23_fu_866_p1(15 - 1 downto 0);
    mul_ln23_fu_870_p1 <= zext_ln23_fu_866_p1(15 - 1 downto 0);
    mul_ln29_fu_284_p1 <= mul_ln29_fu_284_p10(22 - 1 downto 0);
    mul_ln29_fu_284_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_reg_1378),45));
    mul_ln30_fu_936_p0 <= mul_ln30_fu_936_p00(15 - 1 downto 0);
    mul_ln30_fu_936_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_squared_reg_1383),30));
    mul_ln32_fu_288_p1 <= mul_ln32_fu_288_p10(29 - 1 downto 0);
    mul_ln32_fu_288_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_1_fu_973_p3),58));
    newexp_fu_1131_p2 <= std_logic_vector(signed(sext_ln300_fu_1127_p1) - signed(shift_2_fu_1113_p3));
    or_ln282_fu_1202_p2 <= (or_ln306_fu_1150_p2 or icmp_ln282_reg_1366_pp0_iter8_reg);
    or_ln306_fu_1150_p2 <= (tmp_10_fu_1137_p3 or icmp_ln306_fu_1145_p2);
    out_bits_2_fu_1035_p3 <= (tmp_9_reg_1434 & ap_const_lv19_40000);
    out_bits_fu_1028_p3 <= (tmp_8_reg_1429 & ap_const_lv16_8000);
    ref_4oPi_table_100_address0 <= zext_ln378_fu_352_p1(4 - 1 downto 0);

    ref_4oPi_table_100_ce0_local_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            ref_4oPi_table_100_ce0_local <= ap_const_logic_1;
        else 
            ref_4oPi_table_100_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    results_exp_1_fu_1230_p3 <= 
        select_ln259_fu_1188_p3 when (and_ln271_reg_1360_pp0_iter8_reg(0) = '1') else 
        results_exp_fu_1207_p3;
    results_exp_fu_1207_p3 <= 
        select_ln282_fu_1195_p3 when (or_ln282_fu_1202_p2(0) = '1') else 
        empty_fu_1156_p1;
    results_sig_1_fu_1237_p3 <= 
        ap_const_lv23_0 when (and_ln271_reg_1360_pp0_iter8_reg(0) = '1') else 
        results_sig_fu_1222_p3;
    results_sig_fu_1222_p3 <= 
        select_ln282_2_fu_1215_p3 when (or_ln282_fu_1202_p2(0) = '1') else 
        empty_35_fu_1180_p3;
    results_sign_2_fu_781_p2 <= (xor_ln278_fu_776_p2 and din_sign_reg_1265_pp0_iter3_reg);
    results_sign_3_fu_803_p3 <= 
        results_sign_2_fu_781_p2 when (and_ln271_fu_771_p2(0) = '1') else 
        results_sign_4_fu_797_p2;
    results_sign_4_fu_797_p2 <= (xor_ln282_fu_791_p2 and results_sign_fu_758_p3);
    results_sign_fu_758_p3 <= 
        tmp_13_fu_614_p35 when (cos_basis_fu_593_p3(0) = '1') else 
        tmp_14_fu_686_p35;
    second_order_float_sin_cos_K0_address0 <= zext_ln28_fu_893_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K0_ce0_local_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            second_order_float_sin_cos_K0_ce0_local <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    second_order_float_sin_cos_K1_address0 <= zext_ln28_fu_893_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K1_ce0_local_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            second_order_float_sin_cos_K1_ce0_local <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    second_order_float_sin_cos_K2_address0 <= zext_ln28_fu_893_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K2_ce0_local_assign_proc : process(ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            second_order_float_sin_cos_K2_ce0_local <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln259_fu_1188_p3 <= 
        ap_const_lv8_7F when (do_cos_read_reg_1257_pp0_iter8_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln282_2_fu_1215_p3 <= 
        ap_const_lv23_7FFFFF when (icmp_ln282_reg_1366_pp0_iter8_reg(0) = '1') else 
        ap_const_lv23_0;
    select_ln282_fu_1195_p3 <= 
        ap_const_lv8_FF when (icmp_ln282_reg_1366_pp0_iter8_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln453_fu_422_p3 <= 
        Ex_fu_417_p2 when (closepath_reg_1284_pp0_iter3_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln506_1_fu_835_p3 <= 
        lshr_ln506_fu_823_p2 when (tmp_reg_1338(0) = '1') else 
        shl_ln506_fu_829_p2;
    select_ln506_fu_811_p3 <= 
        sub_ln506_reg_1344 when (tmp_reg_1338(0) = '1') else 
        Ex_1_reg_1332;
        sext_ln252_fu_1024_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ex_2_fu_1018_p3),9));

        sext_ln300_fu_1127_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln300_fu_1121_p2),32));

        sext_ln32_1_fu_955_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_1408),30));

        sext_ln32_2_fu_964_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_1413),30));

        sext_ln32_fu_952_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t1_reg_1403),30));

        sext_ln75_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_479_p3),32));

    shift_1_fu_1097_p2 <= std_logic_vector(unsigned(c_1_fu_1070_p3) + unsigned(ap_const_lv32_10));
    shift_2_fu_1113_p3 <= 
        shift_1_fu_1097_p2 when (icmp_ln292_fu_1091_p2(0) = '1') else 
        c_fu_1052_p3;
    shl_ln291_1_fu_1107_p2 <= std_logic_vector(shift_left(unsigned(zext_ln291_1_fu_1103_p1),to_integer(unsigned('0' & c_1_fu_1070_p3(31-1 downto 0)))));
    shl_ln291_fu_1081_p2 <= std_logic_vector(shift_left(unsigned(zext_ln291_fu_1078_p1),to_integer(unsigned('0' & c_fu_1052_p3(31-1 downto 0)))));
    shl_ln379_fu_364_p2 <= std_logic_vector(shift_left(unsigned(ref_4oPi_table_100_q0),to_integer(unsigned('0' & zext_ln379_fu_361_p1(31-1 downto 0)))));
    shl_ln504_fu_507_p2 <= std_logic_vector(shift_left(unsigned(Mx_bits_2_fu_444_p3),to_integer(unsigned('0' & zext_ln504_fu_503_p1(31-1 downto 0)))));
    shl_ln506_fu_829_p2 <= std_logic_vector(shift_left(unsigned(zext_ln506_fu_820_p1),to_integer(unsigned('0' & zext_ln506_1_fu_816_p1(31-1 downto 0)))));
    sin_basis_fu_600_p3 <= 
        tmp_6_fu_547_p19 when (do_cos_read_reg_1257_pp0_iter3_reg(0) = '1') else 
        xor_ln242_fu_587_p2;
    sub_ln506_fu_541_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(Ex_1_fu_527_p2));
    t_2_fu_1244_p4 <= ((results_sign_3_reg_1373_pp0_iter8_reg & results_exp_1_fu_1230_p3) & results_sig_1_fu_1237_p3);
    t_fu_461_p3 <= (tmp_s_fu_451_p4 & ap_const_lv1_1);
    tmp_10_fu_1137_p3 <= newexp_fu_1131_p2(31 downto 31);
    tmp_11_fu_1160_p4 <= shl_ln291_1_fu_1107_p2(27 downto 5);
    tmp_12_fu_1170_p4 <= shl_ln291_fu_1081_p2(27 downto 5);
    tmp_13_fu_614_p33 <= "X";
    tmp_14_fu_686_p33 <= "X";
    
    tmp_1_fu_1042_p4_proc : process(out_bits_fu_1028_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_1_fu_1042_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := out_bits_fu_1028_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for tmp_1_fu_1042_p4_i in 0 to 32-1 loop
                v0_cpy(tmp_1_fu_1042_p4_i) := out_bits_fu_1028_p3(32-1-tmp_1_fu_1042_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_1_fu_1042_p4 <= resvalue(32-1 downto 0);
    end process;

    
    tmp_2_fu_1060_p4_proc : process(out_bits_2_fu_1035_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_2_fu_1060_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := out_bits_2_fu_1035_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for tmp_2_fu_1060_p4_i in 0 to 32-1 loop
                v0_cpy(tmp_2_fu_1060_p4_i) := out_bits_2_fu_1035_p3(32-1-tmp_2_fu_1060_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_2_fu_1060_p4 <= resvalue(32-1 downto 0);
    end process;

    
    tmp_3_fu_469_p4_proc : process(t_fu_461_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(30+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(30+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable tmp_3_fu_469_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(30 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1D(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := t_fu_461_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(30-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(30-1-unsigned(ap_const_lv32_1D(5-1 downto 0)));
            for tmp_3_fu_469_p4_i in 0 to 30-1 loop
                v0_cpy(tmp_3_fu_469_p4_i) := t_fu_461_p3(30-1-tmp_3_fu_469_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(30-1 downto 0)))));
        res_mask := res_mask(30-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_3_fu_469_p4 <= resvalue(30-1 downto 0);
    end process;

    tmp_4_fu_479_p3 <= (ap_const_lv1_1 & tmp_3_fu_469_p4);
    
    tmp_5_fu_491_p3_proc : process(sext_ln75_fu_487_p1)
    begin
        tmp_5_fu_491_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if sext_ln75_fu_487_p1(i) = '1' then
                tmp_5_fu_491_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    tmp_6_fu_547_p17 <= "X";
    tmp_7_fu_846_p4 <= select_ln506_1_fu_835_p3(28 downto 22);
    tmp_s_fu_451_p4 <= Mx_bits_2_fu_444_p3(57 downto 29);
    trunc_ln379_fu_357_p1 <= addr_fu_334_p3(4 - 1 downto 0);
    trunc_ln491_fu_435_p1 <= k_1_fu_429_p3(1 - 1 downto 0);
    xor_ln242_fu_587_p2 <= (tmp_6_fu_547_p19 xor ap_const_lv1_1);
    xor_ln278_fu_776_p2 <= (do_cos_read_reg_1257_pp0_iter3_reg xor ap_const_lv1_1);
    xor_ln282_fu_791_p2 <= (icmp_ln282_fu_786_p2 xor ap_const_lv1_1);
    zext_ln23_fu_866_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_trunc_fu_856_p4),30));
    zext_ln28_fu_893_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_fu_886_p3),64));
    zext_ln291_1_fu_1103_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_shift_1_fu_1087_p1),32));
    zext_ln291_fu_1078_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_reg_1423),32));
    zext_ln378_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_342_p4),64));
    zext_ln379_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln379_reg_1295),100));
    zext_ln504_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_zeros_fu_499_p1),58));
    zext_ln505_fu_523_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_zeros_fu_499_p1),8));
    zext_ln506_1_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln506_fu_811_p3),32));
    zext_ln506_fu_820_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_reg_1326),32));
end behav;
