#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("accel_TDATA", 16, hls_in, 0, "axis", "in_data", 1),
	Port_Property("accel_TVALID", 1, hls_in, 0, "axis", "in_vld", 1),
	Port_Property("accel_TREADY", 1, hls_out, 0, "axis", "in_acc", 1),
	Port_Property("S_tilde_0", 32, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_0_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("S_tilde_1", 32, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_1_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("S_tilde_2", 32, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_2_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("S_tilde_3", 32, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_3_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("S_tilde_4", 32, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_4_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("S_tilde_5", 32, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_5_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("S_tilde_6", 32, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_6_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("S_tilde_7", 32, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_7_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("S_tilde_8", 32, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("S_tilde_8_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "scatter_matrix";
