// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module scatter_matrix_addsub_0_0_ap_fixed_43_4_5_3_0_ap_fixed_43_4_5_3_0_ap_uint_1_s (
        ap_ready,
        a,
        b,
        add,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [42:0] a;
input  [42:0] b;
input  [0:0] add;
output  [42:0] ap_return;
input   ap_rst;

wire   [42:0] add_ln102_fu_40_p2;
wire   [42:0] sub_ln104_fu_34_p2;

assign add_ln102_fu_40_p2 = (b + a);

assign ap_ready = 1'b1;

assign sub_ln104_fu_34_p2 = (a - b);

assign ap_return = ((add[0:0] == 1'b1) ? add_ln102_fu_40_p2 : sub_ln104_fu_34_p2);

endmodule //scatter_matrix_addsub_0_0_ap_fixed_43_4_5_3_0_ap_fixed_43_4_5_3_0_ap_uint_1_s
