// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module scatter_matrix_sin_or_cos_float_s (
        ap_clk,
        ap_rst,
        t_in,
        do_cos,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] t_in;
input  [0:0] do_cos;
output  [31:0] ap_return;
input   ap_ce;

wire   [3:0] ref_4oPi_table_100_address0;
wire   [99:0] ref_4oPi_table_100_q0;
wire   [7:0] second_order_float_sin_cos_K0_address0;
wire   [29:0] second_order_float_sin_cos_K0_q0;
wire   [7:0] second_order_float_sin_cos_K1_address0;
wire  signed [22:0] second_order_float_sin_cos_K1_q0;
wire   [7:0] second_order_float_sin_cos_K2_address0;
wire  signed [14:0] second_order_float_sin_cos_K2_q0;
reg   [0:0] do_cos_read_reg_1257;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] do_cos_read_reg_1257_pp0_iter1_reg;
reg   [0:0] do_cos_read_reg_1257_pp0_iter2_reg;
reg   [0:0] do_cos_read_reg_1257_pp0_iter3_reg;
reg   [0:0] do_cos_read_reg_1257_pp0_iter4_reg;
reg   [0:0] do_cos_read_reg_1257_pp0_iter5_reg;
reg   [0:0] do_cos_read_reg_1257_pp0_iter6_reg;
reg   [0:0] do_cos_read_reg_1257_pp0_iter7_reg;
reg   [0:0] do_cos_read_reg_1257_pp0_iter8_reg;
reg   [0:0] din_sign_reg_1265;
reg   [0:0] din_sign_reg_1265_pp0_iter1_reg;
reg   [0:0] din_sign_reg_1265_pp0_iter2_reg;
reg   [0:0] din_sign_reg_1265_pp0_iter3_reg;
wire   [7:0] din_exp_fu_308_p4;
reg   [7:0] din_exp_reg_1271;
reg   [7:0] din_exp_reg_1271_pp0_iter1_reg;
reg   [7:0] din_exp_reg_1271_pp0_iter2_reg;
reg   [7:0] din_exp_reg_1271_pp0_iter3_reg;
wire   [22:0] din_sig_fu_318_p1;
reg   [22:0] din_sig_reg_1278;
reg   [22:0] din_sig_reg_1278_pp0_iter1_reg;
wire   [0:0] closepath_fu_322_p2;
reg   [0:0] closepath_reg_1284;
reg   [0:0] closepath_reg_1284_pp0_iter1_reg;
reg   [0:0] closepath_reg_1284_pp0_iter2_reg;
reg   [0:0] closepath_reg_1284_pp0_iter3_reg;
wire   [3:0] trunc_ln379_fu_357_p1;
reg   [3:0] trunc_ln379_reg_1295;
reg  signed [79:0] Med_reg_1300;
wire   [0:0] icmp_ln271_1_fu_392_p2;
reg   [0:0] icmp_ln271_1_reg_1310;
reg   [0:0] icmp_ln271_1_reg_1310_pp0_iter3_reg;
reg   [57:0] Mx_bits_reg_1315;
reg   [2:0] k_reg_1321;
reg   [28:0] Mx_reg_1326;
reg   [28:0] Mx_reg_1326_pp0_iter5_reg;
reg   [28:0] Mx_reg_1326_pp0_iter6_reg;
reg   [28:0] Mx_reg_1326_pp0_iter7_reg;
wire   [7:0] Ex_1_fu_527_p2;
reg   [7:0] Ex_1_reg_1332;
reg   [7:0] Ex_1_reg_1332_pp0_iter5_reg;
reg   [7:0] Ex_1_reg_1332_pp0_iter6_reg;
reg   [7:0] Ex_1_reg_1332_pp0_iter7_reg;
reg   [7:0] Ex_1_reg_1332_pp0_iter8_reg;
reg   [0:0] tmp_reg_1338;
wire   [7:0] sub_ln506_fu_541_p2;
reg   [7:0] sub_ln506_reg_1344;
wire   [0:0] cos_basis_fu_593_p3;
reg   [0:0] cos_basis_reg_1349;
reg   [0:0] cos_basis_reg_1349_pp0_iter5_reg;
reg   [0:0] cos_basis_reg_1349_pp0_iter6_reg;
reg   [0:0] cos_basis_reg_1349_pp0_iter7_reg;
reg   [0:0] cos_basis_reg_1349_pp0_iter8_reg;
wire   [0:0] sin_basis_fu_600_p3;
reg   [0:0] sin_basis_reg_1355;
wire   [0:0] and_ln271_fu_771_p2;
reg   [0:0] and_ln271_reg_1360;
reg   [0:0] and_ln271_reg_1360_pp0_iter5_reg;
reg   [0:0] and_ln271_reg_1360_pp0_iter6_reg;
reg   [0:0] and_ln271_reg_1360_pp0_iter7_reg;
reg   [0:0] and_ln271_reg_1360_pp0_iter8_reg;
wire   [0:0] icmp_ln282_fu_786_p2;
reg   [0:0] icmp_ln282_reg_1366;
reg   [0:0] icmp_ln282_reg_1366_pp0_iter5_reg;
reg   [0:0] icmp_ln282_reg_1366_pp0_iter6_reg;
reg   [0:0] icmp_ln282_reg_1366_pp0_iter7_reg;
reg   [0:0] icmp_ln282_reg_1366_pp0_iter8_reg;
wire   [0:0] results_sign_3_fu_803_p3;
reg   [0:0] results_sign_3_reg_1373;
reg   [0:0] results_sign_3_reg_1373_pp0_iter5_reg;
reg   [0:0] results_sign_3_reg_1373_pp0_iter6_reg;
reg   [0:0] results_sign_3_reg_1373_pp0_iter7_reg;
reg   [0:0] results_sign_3_reg_1373_pp0_iter8_reg;
wire   [21:0] B_fu_842_p1;
reg   [21:0] B_reg_1378;
reg   [14:0] B_squared_reg_1383;
reg   [28:0] t1_reg_1403;
reg   [21:0] trunc_ln_reg_1408;
reg   [13:0] trunc_ln1_reg_1413;
wire   [29:0] add_ln32_1_fu_967_p2;
reg  signed [29:0] add_ln32_1_reg_1418;
reg   [28:0] result_reg_1423;
reg   [15:0] tmp_8_reg_1429;
reg   [12:0] tmp_9_reg_1434;
wire   [63:0] zext_ln378_fu_352_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln28_fu_893_p1;
reg    ref_4oPi_table_100_ce0_local;
reg    second_order_float_sin_cos_K0_ce0_local;
reg    second_order_float_sin_cos_K1_ce0_local;
reg    second_order_float_sin_cos_K2_ce0_local;
wire   [21:0] mul_ln29_fu_284_p1;
wire   [28:0] mul_ln32_fu_288_p1;
wire   [23:0] grp_fu_292_p1;
wire   [31:0] data_fu_296_p1;
wire   [7:0] add_ln376_fu_328_p2;
wire   [7:0] addr_fu_334_p3;
wire   [3:0] lshr_ln_fu_342_p4;
wire   [99:0] zext_ln379_fu_361_p1;
wire   [99:0] shl_ln379_fu_364_p2;
wire   [23:0] X_fu_380_p3;
wire   [79:0] grp_fu_292_p2;
wire   [7:0] Ex_fu_417_p2;
wire   [2:0] k_1_fu_429_p3;
wire   [0:0] trunc_ln491_fu_435_p1;
wire   [57:0] Mx_bits_1_fu_439_p2;
wire   [57:0] Mx_bits_2_fu_444_p3;
wire   [28:0] tmp_s_fu_451_p4;
wire   [29:0] t_fu_461_p3;
reg   [29:0] tmp_3_fu_469_p4;
wire   [30:0] tmp_4_fu_479_p3;
wire  signed [31:0] sext_ln75_fu_487_p1;
reg   [31:0] tmp_5_fu_491_p3;
wire   [5:0] Mx_zeros_fu_499_p1;
wire   [57:0] zext_ln504_fu_503_p1;
wire   [57:0] shl_ln504_fu_507_p2;
wire   [7:0] select_ln453_fu_422_p3;
wire   [7:0] zext_ln505_fu_523_p1;
wire   [0:0] tmp_6_fu_547_p17;
wire   [0:0] tmp_6_fu_547_p19;
wire   [0:0] xor_ln242_fu_587_p2;
wire   [0:0] tmp_13_fu_614_p33;
wire   [3:0] index_fu_607_p3;
wire   [0:0] tmp_14_fu_686_p33;
wire   [0:0] tmp_13_fu_614_p35;
wire   [0:0] tmp_14_fu_686_p35;
wire   [0:0] icmp_ln271_fu_766_p2;
wire   [0:0] xor_ln278_fu_776_p2;
wire   [0:0] results_sign_fu_758_p3;
wire   [0:0] xor_ln282_fu_791_p2;
wire   [0:0] results_sign_2_fu_781_p2;
wire   [0:0] results_sign_4_fu_797_p2;
wire   [7:0] select_ln506_fu_811_p3;
wire   [31:0] zext_ln506_fu_820_p1;
wire   [31:0] zext_ln506_1_fu_816_p1;
wire   [31:0] lshr_ln506_fu_823_p2;
wire   [31:0] shl_ln506_fu_829_p2;
wire   [31:0] select_ln506_1_fu_835_p3;
wire   [14:0] B_trunc_fu_856_p4;
wire   [14:0] mul_ln23_fu_870_p0;
wire   [29:0] zext_ln23_fu_866_p1;
wire   [14:0] mul_ln23_fu_870_p1;
wire   [29:0] mul_ln23_fu_870_p2;
wire   [6:0] tmp_7_fu_846_p4;
wire   [7:0] A_fu_886_p3;
wire   [44:0] mul_ln29_fu_284_p2;
wire   [14:0] mul_ln30_fu_936_p0;
wire   [29:0] mul_ln30_fu_936_p2;
wire  signed [29:0] sext_ln32_fu_952_p1;
wire  signed [29:0] sext_ln32_1_fu_955_p1;
wire   [29:0] add_ln32_fu_958_p2;
wire  signed [29:0] sext_ln32_2_fu_964_p1;
wire   [28:0] Mx_1_fu_973_p3;
wire   [57:0] mul_ln32_fu_288_p2;
wire   [7:0] Ex_2_fu_1018_p3;
wire   [31:0] out_bits_fu_1028_p3;
reg   [31:0] tmp_1_fu_1042_p4;
wire   [31:0] out_bits_2_fu_1035_p3;
reg   [31:0] tmp_2_fu_1060_p4;
wire   [31:0] zext_ln291_fu_1078_p1;
reg   [31:0] c_fu_1052_p3;
wire   [31:0] shl_ln291_fu_1081_p2;
reg   [31:0] c_1_fu_1070_p3;
wire   [27:0] in_shift_1_fu_1087_p1;
wire   [31:0] zext_ln291_1_fu_1103_p1;
wire   [0:0] icmp_ln292_fu_1091_p2;
wire   [31:0] shift_1_fu_1097_p2;
wire  signed [8:0] sext_ln252_fu_1024_p1;
wire   [8:0] add_ln300_fu_1121_p2;
wire  signed [31:0] sext_ln300_fu_1127_p1;
wire   [31:0] shift_2_fu_1113_p3;
wire   [31:0] newexp_fu_1131_p2;
wire   [0:0] tmp_10_fu_1137_p3;
wire   [0:0] icmp_ln306_fu_1145_p2;
wire   [31:0] shl_ln291_1_fu_1107_p2;
wire   [22:0] tmp_11_fu_1160_p4;
wire   [22:0] tmp_12_fu_1170_p4;
wire   [0:0] or_ln306_fu_1150_p2;
wire   [0:0] or_ln282_fu_1202_p2;
wire   [7:0] select_ln282_fu_1195_p3;
wire   [7:0] empty_fu_1156_p1;
wire   [22:0] select_ln282_2_fu_1215_p3;
wire   [22:0] empty_35_fu_1180_p3;
wire   [7:0] select_ln259_fu_1188_p3;
wire   [7:0] results_exp_fu_1207_p3;
wire   [22:0] results_sig_fu_1222_p3;
wire   [7:0] results_exp_1_fu_1230_p3;
wire   [22:0] results_sig_1_fu_1237_p3;
wire   [31:0] t_2_fu_1244_p4;
reg    grp_fu_292_ce;
reg   [31:0] t_in_int_reg;
reg   [0:0] do_cos_int_reg;
wire   [79:0] grp_fu_292_p10;
wire   [44:0] mul_ln29_fu_284_p10;
wire   [29:0] mul_ln30_fu_936_p00;
wire   [57:0] mul_ln32_fu_288_p10;
wire   [2:0] tmp_6_fu_547_p1;
wire   [2:0] tmp_6_fu_547_p3;
wire   [2:0] tmp_6_fu_547_p5;
wire   [2:0] tmp_6_fu_547_p7;
wire  signed [2:0] tmp_6_fu_547_p9;
wire  signed [2:0] tmp_6_fu_547_p11;
wire  signed [2:0] tmp_6_fu_547_p13;
wire  signed [2:0] tmp_6_fu_547_p15;
wire   [3:0] tmp_13_fu_614_p1;
wire   [3:0] tmp_13_fu_614_p3;
wire   [3:0] tmp_13_fu_614_p5;
wire   [3:0] tmp_13_fu_614_p7;
wire   [3:0] tmp_13_fu_614_p9;
wire   [3:0] tmp_13_fu_614_p11;
wire   [3:0] tmp_13_fu_614_p13;
wire   [3:0] tmp_13_fu_614_p15;
wire  signed [3:0] tmp_13_fu_614_p17;
wire  signed [3:0] tmp_13_fu_614_p19;
wire  signed [3:0] tmp_13_fu_614_p21;
wire  signed [3:0] tmp_13_fu_614_p23;
wire  signed [3:0] tmp_13_fu_614_p25;
wire  signed [3:0] tmp_13_fu_614_p27;
wire  signed [3:0] tmp_13_fu_614_p29;
wire  signed [3:0] tmp_13_fu_614_p31;
wire   [3:0] tmp_14_fu_686_p1;
wire   [3:0] tmp_14_fu_686_p3;
wire   [3:0] tmp_14_fu_686_p5;
wire   [3:0] tmp_14_fu_686_p7;
wire   [3:0] tmp_14_fu_686_p9;
wire   [3:0] tmp_14_fu_686_p11;
wire   [3:0] tmp_14_fu_686_p13;
wire   [3:0] tmp_14_fu_686_p15;
wire  signed [3:0] tmp_14_fu_686_p17;
wire  signed [3:0] tmp_14_fu_686_p19;
wire  signed [3:0] tmp_14_fu_686_p21;
wire  signed [3:0] tmp_14_fu_686_p23;
wire  signed [3:0] tmp_14_fu_686_p25;
wire  signed [3:0] tmp_14_fu_686_p27;
wire  signed [3:0] tmp_14_fu_686_p29;
wire  signed [3:0] tmp_14_fu_686_p31;
wire    ap_ce_reg;

scatter_matrix_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_address0),
    .ce0(ref_4oPi_table_100_ce0_local),
    .q0(ref_4oPi_table_100_q0)
);

scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K0_address0),
    .ce0(second_order_float_sin_cos_K0_ce0_local),
    .q0(second_order_float_sin_cos_K0_q0)
);

scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K1_address0),
    .ce0(second_order_float_sin_cos_K1_ce0_local),
    .q0(second_order_float_sin_cos_K1_q0)
);

scatter_matrix_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K2_address0),
    .ce0(second_order_float_sin_cos_K2_ce0_local),
    .q0(second_order_float_sin_cos_K2_q0)
);

scatter_matrix_mul_23s_22ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 45 ))
mul_23s_22ns_45_1_1_U21(
    .din0(second_order_float_sin_cos_K1_q0),
    .din1(mul_ln29_fu_284_p1),
    .dout(mul_ln29_fu_284_p2)
);

scatter_matrix_mul_30s_29ns_58_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
mul_30s_29ns_58_1_1_U22(
    .din0(add_ln32_1_reg_1418),
    .din1(mul_ln32_fu_288_p1),
    .dout(mul_ln32_fu_288_p2)
);

scatter_matrix_mul_80s_24ns_80_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 80 ))
mul_80s_24ns_80_2_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Med_reg_1300),
    .din1(grp_fu_292_p1),
    .ce(grp_fu_292_ce),
    .dout(grp_fu_292_p2)
);

(* dissolve_hierarchy = "yes" *) scatter_matrix_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U24(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .def(tmp_6_fu_547_p17),
    .sel(k_1_fu_429_p3),
    .dout(tmp_6_fu_547_p19)
);

(* dissolve_hierarchy = "yes" *) scatter_matrix_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U25(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_13_fu_614_p33),
    .sel(index_fu_607_p3),
    .dout(tmp_13_fu_614_p35)
);

(* dissolve_hierarchy = "yes" *) scatter_matrix_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U26(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_14_fu_686_p33),
    .sel(index_fu_607_p3),
    .dout(tmp_14_fu_686_p35)
);

scatter_matrix_mul_15ns_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15ns_30_1_1_U27(
    .din0(mul_ln23_fu_870_p0),
    .din1(mul_ln23_fu_870_p1),
    .dout(mul_ln23_fu_870_p2)
);

scatter_matrix_mul_15ns_15s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15s_30_1_1_U28(
    .din0(mul_ln30_fu_936_p0),
    .din1(second_order_float_sin_cos_K2_q0),
    .dout(mul_ln30_fu_936_p2)
);

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        B_reg_1378 <= B_fu_842_p1;
        B_squared_reg_1383 <= {{mul_ln23_fu_870_p2[29:15]}};
        Ex_1_reg_1332 <= Ex_1_fu_527_p2;
        Ex_1_reg_1332_pp0_iter5_reg <= Ex_1_reg_1332;
        Ex_1_reg_1332_pp0_iter6_reg <= Ex_1_reg_1332_pp0_iter5_reg;
        Ex_1_reg_1332_pp0_iter7_reg <= Ex_1_reg_1332_pp0_iter6_reg;
        Ex_1_reg_1332_pp0_iter8_reg <= Ex_1_reg_1332_pp0_iter7_reg;
        Med_reg_1300 <= {{shl_ln379_fu_364_p2[99:20]}};
        Mx_bits_reg_1315 <= {{grp_fu_292_p2[76:19]}};
        Mx_reg_1326 <= {{shl_ln504_fu_507_p2[57:29]}};
        Mx_reg_1326_pp0_iter5_reg <= Mx_reg_1326;
        Mx_reg_1326_pp0_iter6_reg <= Mx_reg_1326_pp0_iter5_reg;
        Mx_reg_1326_pp0_iter7_reg <= Mx_reg_1326_pp0_iter6_reg;
        add_ln32_1_reg_1418 <= add_ln32_1_fu_967_p2;
        and_ln271_reg_1360 <= and_ln271_fu_771_p2;
        and_ln271_reg_1360_pp0_iter5_reg <= and_ln271_reg_1360;
        and_ln271_reg_1360_pp0_iter6_reg <= and_ln271_reg_1360_pp0_iter5_reg;
        and_ln271_reg_1360_pp0_iter7_reg <= and_ln271_reg_1360_pp0_iter6_reg;
        and_ln271_reg_1360_pp0_iter8_reg <= and_ln271_reg_1360_pp0_iter7_reg;
        closepath_reg_1284 <= closepath_fu_322_p2;
        closepath_reg_1284_pp0_iter1_reg <= closepath_reg_1284;
        closepath_reg_1284_pp0_iter2_reg <= closepath_reg_1284_pp0_iter1_reg;
        closepath_reg_1284_pp0_iter3_reg <= closepath_reg_1284_pp0_iter2_reg;
        cos_basis_reg_1349 <= cos_basis_fu_593_p3;
        cos_basis_reg_1349_pp0_iter5_reg <= cos_basis_reg_1349;
        cos_basis_reg_1349_pp0_iter6_reg <= cos_basis_reg_1349_pp0_iter5_reg;
        cos_basis_reg_1349_pp0_iter7_reg <= cos_basis_reg_1349_pp0_iter6_reg;
        cos_basis_reg_1349_pp0_iter8_reg <= cos_basis_reg_1349_pp0_iter7_reg;
        din_exp_reg_1271 <= {{data_fu_296_p1[30:23]}};
        din_exp_reg_1271_pp0_iter1_reg <= din_exp_reg_1271;
        din_exp_reg_1271_pp0_iter2_reg <= din_exp_reg_1271_pp0_iter1_reg;
        din_exp_reg_1271_pp0_iter3_reg <= din_exp_reg_1271_pp0_iter2_reg;
        din_sig_reg_1278 <= din_sig_fu_318_p1;
        din_sig_reg_1278_pp0_iter1_reg <= din_sig_reg_1278;
        din_sign_reg_1265 <= data_fu_296_p1[32'd31];
        din_sign_reg_1265_pp0_iter1_reg <= din_sign_reg_1265;
        din_sign_reg_1265_pp0_iter2_reg <= din_sign_reg_1265_pp0_iter1_reg;
        din_sign_reg_1265_pp0_iter3_reg <= din_sign_reg_1265_pp0_iter2_reg;
        do_cos_read_reg_1257 <= do_cos_int_reg;
        do_cos_read_reg_1257_pp0_iter1_reg <= do_cos_read_reg_1257;
        do_cos_read_reg_1257_pp0_iter2_reg <= do_cos_read_reg_1257_pp0_iter1_reg;
        do_cos_read_reg_1257_pp0_iter3_reg <= do_cos_read_reg_1257_pp0_iter2_reg;
        do_cos_read_reg_1257_pp0_iter4_reg <= do_cos_read_reg_1257_pp0_iter3_reg;
        do_cos_read_reg_1257_pp0_iter5_reg <= do_cos_read_reg_1257_pp0_iter4_reg;
        do_cos_read_reg_1257_pp0_iter6_reg <= do_cos_read_reg_1257_pp0_iter5_reg;
        do_cos_read_reg_1257_pp0_iter7_reg <= do_cos_read_reg_1257_pp0_iter6_reg;
        do_cos_read_reg_1257_pp0_iter8_reg <= do_cos_read_reg_1257_pp0_iter7_reg;
        icmp_ln271_1_reg_1310 <= icmp_ln271_1_fu_392_p2;
        icmp_ln271_1_reg_1310_pp0_iter3_reg <= icmp_ln271_1_reg_1310;
        icmp_ln282_reg_1366 <= icmp_ln282_fu_786_p2;
        icmp_ln282_reg_1366_pp0_iter5_reg <= icmp_ln282_reg_1366;
        icmp_ln282_reg_1366_pp0_iter6_reg <= icmp_ln282_reg_1366_pp0_iter5_reg;
        icmp_ln282_reg_1366_pp0_iter7_reg <= icmp_ln282_reg_1366_pp0_iter6_reg;
        icmp_ln282_reg_1366_pp0_iter8_reg <= icmp_ln282_reg_1366_pp0_iter7_reg;
        k_reg_1321 <= {{grp_fu_292_p2[79:77]}};
        result_reg_1423 <= {{mul_ln32_fu_288_p2[57:29]}};
        results_sign_3_reg_1373 <= results_sign_3_fu_803_p3;
        results_sign_3_reg_1373_pp0_iter5_reg <= results_sign_3_reg_1373;
        results_sign_3_reg_1373_pp0_iter6_reg <= results_sign_3_reg_1373_pp0_iter5_reg;
        results_sign_3_reg_1373_pp0_iter7_reg <= results_sign_3_reg_1373_pp0_iter6_reg;
        results_sign_3_reg_1373_pp0_iter8_reg <= results_sign_3_reg_1373_pp0_iter7_reg;
        sin_basis_reg_1355 <= sin_basis_fu_600_p3;
        sub_ln506_reg_1344 <= sub_ln506_fu_541_p2;
        t1_reg_1403 <= {{second_order_float_sin_cos_K0_q0[29:1]}};
        tmp_8_reg_1429 <= {{mul_ln32_fu_288_p2[57:42]}};
        tmp_9_reg_1434 <= {{mul_ln32_fu_288_p2[41:29]}};
        tmp_reg_1338 <= Ex_1_fu_527_p2[32'd7];
        trunc_ln1_reg_1413 <= {{mul_ln30_fu_936_p2[29:16]}};
        trunc_ln379_reg_1295 <= trunc_ln379_fu_357_p1;
        trunc_ln_reg_1408 <= {{mul_ln29_fu_284_p2[44:23]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        do_cos_int_reg <= do_cos;
        t_in_int_reg <= t_in;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_292_ce = 1'b1;
    end else begin
        grp_fu_292_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        ref_4oPi_table_100_ce0_local = 1'b1;
    end else begin
        ref_4oPi_table_100_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        second_order_float_sin_cos_K0_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        second_order_float_sin_cos_K1_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        second_order_float_sin_cos_K2_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K2_ce0_local = 1'b0;
    end
end

assign A_fu_886_p3 = {{sin_basis_reg_1355}, {tmp_7_fu_846_p4}};

assign B_fu_842_p1 = select_ln506_1_fu_835_p3[21:0];

assign B_trunc_fu_856_p4 = {{select_ln506_1_fu_835_p3[21:7]}};

assign Ex_1_fu_527_p2 = (select_ln453_fu_422_p3 - zext_ln505_fu_523_p1);

assign Ex_2_fu_1018_p3 = ((cos_basis_reg_1349_pp0_iter8_reg[0:0] == 1'b1) ? 8'd0 : Ex_1_reg_1332_pp0_iter8_reg);

assign Ex_fu_417_p2 = ($signed(din_exp_reg_1271_pp0_iter3_reg) + $signed(8'd131));

assign Mx_1_fu_973_p3 = ((cos_basis_reg_1349_pp0_iter7_reg[0:0] == 1'b1) ? 29'd536870911 : Mx_reg_1326_pp0_iter7_reg);

assign Mx_bits_1_fu_439_p2 = (58'd0 - Mx_bits_reg_1315);

assign Mx_bits_2_fu_444_p3 = ((trunc_ln491_fu_435_p1[0:0] == 1'b1) ? Mx_bits_1_fu_439_p2 : Mx_bits_reg_1315);

assign Mx_zeros_fu_499_p1 = tmp_5_fu_491_p3[5:0];

assign X_fu_380_p3 = {{1'd1}, {din_sig_reg_1278_pp0_iter1_reg}};

assign add_ln300_fu_1121_p2 = ($signed(sext_ln252_fu_1024_p1) + $signed(9'd127));

assign add_ln32_1_fu_967_p2 = ($signed(add_ln32_fu_958_p2) + $signed(sext_ln32_2_fu_964_p1));

assign add_ln32_fu_958_p2 = ($signed(sext_ln32_fu_952_p1) + $signed(sext_ln32_1_fu_955_p1));

assign add_ln376_fu_328_p2 = ($signed(din_exp_fu_308_p4) + $signed(8'd194));

assign addr_fu_334_p3 = ((closepath_fu_322_p2[0:0] == 1'b1) ? 8'd63 : add_ln376_fu_328_p2);

assign and_ln271_fu_771_p2 = (icmp_ln271_fu_766_p2 & icmp_ln271_1_reg_1310_pp0_iter3_reg);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = t_2_fu_1244_p4;


always @ (tmp_2_fu_1060_p4) begin
    if (tmp_2_fu_1060_p4[0] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd0;
    end else if (tmp_2_fu_1060_p4[1] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd1;
    end else if (tmp_2_fu_1060_p4[2] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd2;
    end else if (tmp_2_fu_1060_p4[3] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd3;
    end else if (tmp_2_fu_1060_p4[4] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd4;
    end else if (tmp_2_fu_1060_p4[5] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd5;
    end else if (tmp_2_fu_1060_p4[6] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd6;
    end else if (tmp_2_fu_1060_p4[7] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd7;
    end else if (tmp_2_fu_1060_p4[8] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd8;
    end else if (tmp_2_fu_1060_p4[9] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd9;
    end else if (tmp_2_fu_1060_p4[10] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd10;
    end else if (tmp_2_fu_1060_p4[11] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd11;
    end else if (tmp_2_fu_1060_p4[12] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd12;
    end else if (tmp_2_fu_1060_p4[13] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd13;
    end else if (tmp_2_fu_1060_p4[14] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd14;
    end else if (tmp_2_fu_1060_p4[15] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd15;
    end else if (tmp_2_fu_1060_p4[16] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd16;
    end else if (tmp_2_fu_1060_p4[17] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd17;
    end else if (tmp_2_fu_1060_p4[18] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd18;
    end else if (tmp_2_fu_1060_p4[19] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd19;
    end else if (tmp_2_fu_1060_p4[20] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd20;
    end else if (tmp_2_fu_1060_p4[21] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd21;
    end else if (tmp_2_fu_1060_p4[22] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd22;
    end else if (tmp_2_fu_1060_p4[23] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd23;
    end else if (tmp_2_fu_1060_p4[24] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd24;
    end else if (tmp_2_fu_1060_p4[25] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd25;
    end else if (tmp_2_fu_1060_p4[26] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd26;
    end else if (tmp_2_fu_1060_p4[27] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd27;
    end else if (tmp_2_fu_1060_p4[28] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd28;
    end else if (tmp_2_fu_1060_p4[29] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd29;
    end else if (tmp_2_fu_1060_p4[30] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd30;
    end else if (tmp_2_fu_1060_p4[31] == 1'b1) begin
        c_1_fu_1070_p3 = 32'd31;
    end else begin
        c_1_fu_1070_p3 = 32'd32;
    end
end


always @ (tmp_1_fu_1042_p4) begin
    if (tmp_1_fu_1042_p4[0] == 1'b1) begin
        c_fu_1052_p3 = 32'd0;
    end else if (tmp_1_fu_1042_p4[1] == 1'b1) begin
        c_fu_1052_p3 = 32'd1;
    end else if (tmp_1_fu_1042_p4[2] == 1'b1) begin
        c_fu_1052_p3 = 32'd2;
    end else if (tmp_1_fu_1042_p4[3] == 1'b1) begin
        c_fu_1052_p3 = 32'd3;
    end else if (tmp_1_fu_1042_p4[4] == 1'b1) begin
        c_fu_1052_p3 = 32'd4;
    end else if (tmp_1_fu_1042_p4[5] == 1'b1) begin
        c_fu_1052_p3 = 32'd5;
    end else if (tmp_1_fu_1042_p4[6] == 1'b1) begin
        c_fu_1052_p3 = 32'd6;
    end else if (tmp_1_fu_1042_p4[7] == 1'b1) begin
        c_fu_1052_p3 = 32'd7;
    end else if (tmp_1_fu_1042_p4[8] == 1'b1) begin
        c_fu_1052_p3 = 32'd8;
    end else if (tmp_1_fu_1042_p4[9] == 1'b1) begin
        c_fu_1052_p3 = 32'd9;
    end else if (tmp_1_fu_1042_p4[10] == 1'b1) begin
        c_fu_1052_p3 = 32'd10;
    end else if (tmp_1_fu_1042_p4[11] == 1'b1) begin
        c_fu_1052_p3 = 32'd11;
    end else if (tmp_1_fu_1042_p4[12] == 1'b1) begin
        c_fu_1052_p3 = 32'd12;
    end else if (tmp_1_fu_1042_p4[13] == 1'b1) begin
        c_fu_1052_p3 = 32'd13;
    end else if (tmp_1_fu_1042_p4[14] == 1'b1) begin
        c_fu_1052_p3 = 32'd14;
    end else if (tmp_1_fu_1042_p4[15] == 1'b1) begin
        c_fu_1052_p3 = 32'd15;
    end else if (tmp_1_fu_1042_p4[16] == 1'b1) begin
        c_fu_1052_p3 = 32'd16;
    end else if (tmp_1_fu_1042_p4[17] == 1'b1) begin
        c_fu_1052_p3 = 32'd17;
    end else if (tmp_1_fu_1042_p4[18] == 1'b1) begin
        c_fu_1052_p3 = 32'd18;
    end else if (tmp_1_fu_1042_p4[19] == 1'b1) begin
        c_fu_1052_p3 = 32'd19;
    end else if (tmp_1_fu_1042_p4[20] == 1'b1) begin
        c_fu_1052_p3 = 32'd20;
    end else if (tmp_1_fu_1042_p4[21] == 1'b1) begin
        c_fu_1052_p3 = 32'd21;
    end else if (tmp_1_fu_1042_p4[22] == 1'b1) begin
        c_fu_1052_p3 = 32'd22;
    end else if (tmp_1_fu_1042_p4[23] == 1'b1) begin
        c_fu_1052_p3 = 32'd23;
    end else if (tmp_1_fu_1042_p4[24] == 1'b1) begin
        c_fu_1052_p3 = 32'd24;
    end else if (tmp_1_fu_1042_p4[25] == 1'b1) begin
        c_fu_1052_p3 = 32'd25;
    end else if (tmp_1_fu_1042_p4[26] == 1'b1) begin
        c_fu_1052_p3 = 32'd26;
    end else if (tmp_1_fu_1042_p4[27] == 1'b1) begin
        c_fu_1052_p3 = 32'd27;
    end else if (tmp_1_fu_1042_p4[28] == 1'b1) begin
        c_fu_1052_p3 = 32'd28;
    end else if (tmp_1_fu_1042_p4[29] == 1'b1) begin
        c_fu_1052_p3 = 32'd29;
    end else if (tmp_1_fu_1042_p4[30] == 1'b1) begin
        c_fu_1052_p3 = 32'd30;
    end else if (tmp_1_fu_1042_p4[31] == 1'b1) begin
        c_fu_1052_p3 = 32'd31;
    end else begin
        c_fu_1052_p3 = 32'd32;
    end
end

assign closepath_fu_322_p2 = ((din_exp_fu_308_p4 < 8'd126) ? 1'b1 : 1'b0);

assign cos_basis_fu_593_p3 = ((do_cos_read_reg_1257_pp0_iter3_reg[0:0] == 1'b1) ? xor_ln242_fu_587_p2 : tmp_6_fu_547_p19);

assign data_fu_296_p1 = t_in_int_reg;

assign din_exp_fu_308_p4 = {{data_fu_296_p1[30:23]}};

assign din_sig_fu_318_p1 = data_fu_296_p1[22:0];

assign empty_35_fu_1180_p3 = ((icmp_ln292_fu_1091_p2[0:0] == 1'b1) ? tmp_11_fu_1160_p4 : tmp_12_fu_1170_p4);

assign empty_fu_1156_p1 = newexp_fu_1131_p2[7:0];

assign grp_fu_292_p1 = grp_fu_292_p10;

assign grp_fu_292_p10 = X_fu_380_p3;

assign icmp_ln271_1_fu_392_p2 = ((din_sig_reg_1278_pp0_iter1_reg == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_766_p2 = ((din_exp_reg_1271_pp0_iter3_reg == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln282_fu_786_p2 = ((din_exp_reg_1271_pp0_iter3_reg == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln292_fu_1091_p2 = ((c_fu_1052_p3 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln306_fu_1145_p2 = ((result_reg_1423 == 29'd0) ? 1'b1 : 1'b0);

assign in_shift_1_fu_1087_p1 = shl_ln291_fu_1081_p2[27:0];

assign index_fu_607_p3 = {{din_sign_reg_1265_pp0_iter3_reg}, {k_1_fu_429_p3}};

assign k_1_fu_429_p3 = ((closepath_reg_1284_pp0_iter3_reg[0:0] == 1'b1) ? 3'd0 : k_reg_1321);

assign lshr_ln506_fu_823_p2 = zext_ln506_fu_820_p1 >> zext_ln506_1_fu_816_p1;

assign lshr_ln_fu_342_p4 = {{addr_fu_334_p3[7:4]}};

assign mul_ln23_fu_870_p0 = zext_ln23_fu_866_p1;

assign mul_ln23_fu_870_p1 = zext_ln23_fu_866_p1;

assign mul_ln29_fu_284_p1 = mul_ln29_fu_284_p10;

assign mul_ln29_fu_284_p10 = B_reg_1378;

assign mul_ln30_fu_936_p0 = mul_ln30_fu_936_p00;

assign mul_ln30_fu_936_p00 = B_squared_reg_1383;

assign mul_ln32_fu_288_p1 = mul_ln32_fu_288_p10;

assign mul_ln32_fu_288_p10 = Mx_1_fu_973_p3;

assign newexp_fu_1131_p2 = ($signed(sext_ln300_fu_1127_p1) - $signed(shift_2_fu_1113_p3));

assign or_ln282_fu_1202_p2 = (or_ln306_fu_1150_p2 | icmp_ln282_reg_1366_pp0_iter8_reg);

assign or_ln306_fu_1150_p2 = (tmp_10_fu_1137_p3 | icmp_ln306_fu_1145_p2);

assign out_bits_2_fu_1035_p3 = {{tmp_9_reg_1434}, {19'd262144}};

assign out_bits_fu_1028_p3 = {{tmp_8_reg_1429}, {16'd32768}};

assign ref_4oPi_table_100_address0 = zext_ln378_fu_352_p1;

assign results_exp_1_fu_1230_p3 = ((and_ln271_reg_1360_pp0_iter8_reg[0:0] == 1'b1) ? select_ln259_fu_1188_p3 : results_exp_fu_1207_p3);

assign results_exp_fu_1207_p3 = ((or_ln282_fu_1202_p2[0:0] == 1'b1) ? select_ln282_fu_1195_p3 : empty_fu_1156_p1);

assign results_sig_1_fu_1237_p3 = ((and_ln271_reg_1360_pp0_iter8_reg[0:0] == 1'b1) ? 23'd0 : results_sig_fu_1222_p3);

assign results_sig_fu_1222_p3 = ((or_ln282_fu_1202_p2[0:0] == 1'b1) ? select_ln282_2_fu_1215_p3 : empty_35_fu_1180_p3);

assign results_sign_2_fu_781_p2 = (xor_ln278_fu_776_p2 & din_sign_reg_1265_pp0_iter3_reg);

assign results_sign_3_fu_803_p3 = ((and_ln271_fu_771_p2[0:0] == 1'b1) ? results_sign_2_fu_781_p2 : results_sign_4_fu_797_p2);

assign results_sign_4_fu_797_p2 = (xor_ln282_fu_791_p2 & results_sign_fu_758_p3);

assign results_sign_fu_758_p3 = ((cos_basis_fu_593_p3[0:0] == 1'b1) ? tmp_13_fu_614_p35 : tmp_14_fu_686_p35);

assign second_order_float_sin_cos_K0_address0 = zext_ln28_fu_893_p1;

assign second_order_float_sin_cos_K1_address0 = zext_ln28_fu_893_p1;

assign second_order_float_sin_cos_K2_address0 = zext_ln28_fu_893_p1;

assign select_ln259_fu_1188_p3 = ((do_cos_read_reg_1257_pp0_iter8_reg[0:0] == 1'b1) ? 8'd127 : 8'd0);

assign select_ln282_2_fu_1215_p3 = ((icmp_ln282_reg_1366_pp0_iter8_reg[0:0] == 1'b1) ? 23'd8388607 : 23'd0);

assign select_ln282_fu_1195_p3 = ((icmp_ln282_reg_1366_pp0_iter8_reg[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln453_fu_422_p3 = ((closepath_reg_1284_pp0_iter3_reg[0:0] == 1'b1) ? Ex_fu_417_p2 : 8'd0);

assign select_ln506_1_fu_835_p3 = ((tmp_reg_1338[0:0] == 1'b1) ? lshr_ln506_fu_823_p2 : shl_ln506_fu_829_p2);

assign select_ln506_fu_811_p3 = ((tmp_reg_1338[0:0] == 1'b1) ? sub_ln506_reg_1344 : Ex_1_reg_1332);

assign sext_ln252_fu_1024_p1 = $signed(Ex_2_fu_1018_p3);

assign sext_ln300_fu_1127_p1 = $signed(add_ln300_fu_1121_p2);

assign sext_ln32_1_fu_955_p1 = $signed(trunc_ln_reg_1408);

assign sext_ln32_2_fu_964_p1 = $signed(trunc_ln1_reg_1413);

assign sext_ln32_fu_952_p1 = $signed(t1_reg_1403);

assign sext_ln75_fu_487_p1 = $signed(tmp_4_fu_479_p3);

assign shift_1_fu_1097_p2 = (c_1_fu_1070_p3 + 32'd16);

assign shift_2_fu_1113_p3 = ((icmp_ln292_fu_1091_p2[0:0] == 1'b1) ? shift_1_fu_1097_p2 : c_fu_1052_p3);

assign shl_ln291_1_fu_1107_p2 = zext_ln291_1_fu_1103_p1 << c_1_fu_1070_p3;

assign shl_ln291_fu_1081_p2 = zext_ln291_fu_1078_p1 << c_fu_1052_p3;

assign shl_ln379_fu_364_p2 = ref_4oPi_table_100_q0 << zext_ln379_fu_361_p1;

assign shl_ln504_fu_507_p2 = Mx_bits_2_fu_444_p3 << zext_ln504_fu_503_p1;

assign shl_ln506_fu_829_p2 = zext_ln506_fu_820_p1 << zext_ln506_1_fu_816_p1;

assign sin_basis_fu_600_p3 = ((do_cos_read_reg_1257_pp0_iter3_reg[0:0] == 1'b1) ? tmp_6_fu_547_p19 : xor_ln242_fu_587_p2);

assign sub_ln506_fu_541_p2 = (8'd0 - Ex_1_fu_527_p2);

assign t_2_fu_1244_p4 = {{{results_sign_3_reg_1373_pp0_iter8_reg}, {results_exp_1_fu_1230_p3}}, {results_sig_1_fu_1237_p3}};

assign t_fu_461_p3 = {{tmp_s_fu_451_p4}, {1'd1}};

assign tmp_10_fu_1137_p3 = newexp_fu_1131_p2[32'd31];

assign tmp_11_fu_1160_p4 = {{shl_ln291_1_fu_1107_p2[27:5]}};

assign tmp_12_fu_1170_p4 = {{shl_ln291_fu_1081_p2[27:5]}};

assign tmp_13_fu_614_p33 = 'bx;

assign tmp_14_fu_686_p33 = 'bx;

integer ap_tvar_int_0;

always @ (out_bits_fu_1028_p3) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            tmp_1_fu_1042_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_1_fu_1042_p4[ap_tvar_int_0] = out_bits_fu_1028_p3[31 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (out_bits_2_fu_1035_p3) begin
    for (ap_tvar_int_1 = 32 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 31 - 0) begin
            tmp_2_fu_1060_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_2_fu_1060_p4[ap_tvar_int_1] = out_bits_2_fu_1035_p3[31 - ap_tvar_int_1];
        end
    end
end

integer ap_tvar_int_2;

always @ (t_fu_461_p3) begin
    for (ap_tvar_int_2 = 30 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 29 - 0) begin
            tmp_3_fu_469_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_3_fu_469_p4[ap_tvar_int_2] = t_fu_461_p3[29 - ap_tvar_int_2];
        end
    end
end

assign tmp_4_fu_479_p3 = {{1'd1}, {tmp_3_fu_469_p4}};


always @ (sext_ln75_fu_487_p1) begin
    if (sext_ln75_fu_487_p1[0] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd0;
    end else if (sext_ln75_fu_487_p1[1] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd1;
    end else if (sext_ln75_fu_487_p1[2] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd2;
    end else if (sext_ln75_fu_487_p1[3] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd3;
    end else if (sext_ln75_fu_487_p1[4] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd4;
    end else if (sext_ln75_fu_487_p1[5] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd5;
    end else if (sext_ln75_fu_487_p1[6] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd6;
    end else if (sext_ln75_fu_487_p1[7] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd7;
    end else if (sext_ln75_fu_487_p1[8] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd8;
    end else if (sext_ln75_fu_487_p1[9] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd9;
    end else if (sext_ln75_fu_487_p1[10] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd10;
    end else if (sext_ln75_fu_487_p1[11] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd11;
    end else if (sext_ln75_fu_487_p1[12] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd12;
    end else if (sext_ln75_fu_487_p1[13] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd13;
    end else if (sext_ln75_fu_487_p1[14] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd14;
    end else if (sext_ln75_fu_487_p1[15] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd15;
    end else if (sext_ln75_fu_487_p1[16] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd16;
    end else if (sext_ln75_fu_487_p1[17] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd17;
    end else if (sext_ln75_fu_487_p1[18] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd18;
    end else if (sext_ln75_fu_487_p1[19] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd19;
    end else if (sext_ln75_fu_487_p1[20] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd20;
    end else if (sext_ln75_fu_487_p1[21] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd21;
    end else if (sext_ln75_fu_487_p1[22] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd22;
    end else if (sext_ln75_fu_487_p1[23] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd23;
    end else if (sext_ln75_fu_487_p1[24] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd24;
    end else if (sext_ln75_fu_487_p1[25] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd25;
    end else if (sext_ln75_fu_487_p1[26] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd26;
    end else if (sext_ln75_fu_487_p1[27] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd27;
    end else if (sext_ln75_fu_487_p1[28] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd28;
    end else if (sext_ln75_fu_487_p1[29] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd29;
    end else if (sext_ln75_fu_487_p1[30] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd30;
    end else if (sext_ln75_fu_487_p1[31] == 1'b1) begin
        tmp_5_fu_491_p3 = 32'd31;
    end else begin
        tmp_5_fu_491_p3 = 32'd32;
    end
end

assign tmp_6_fu_547_p17 = 'bx;

assign tmp_7_fu_846_p4 = {{select_ln506_1_fu_835_p3[28:22]}};

assign tmp_s_fu_451_p4 = {{Mx_bits_2_fu_444_p3[57:29]}};

assign trunc_ln379_fu_357_p1 = addr_fu_334_p3[3:0];

assign trunc_ln491_fu_435_p1 = k_1_fu_429_p3[0:0];

assign xor_ln242_fu_587_p2 = (tmp_6_fu_547_p19 ^ 1'd1);

assign xor_ln278_fu_776_p2 = (do_cos_read_reg_1257_pp0_iter3_reg ^ 1'd1);

assign xor_ln282_fu_791_p2 = (icmp_ln282_fu_786_p2 ^ 1'd1);

assign zext_ln23_fu_866_p1 = B_trunc_fu_856_p4;

assign zext_ln28_fu_893_p1 = A_fu_886_p3;

assign zext_ln291_1_fu_1103_p1 = in_shift_1_fu_1087_p1;

assign zext_ln291_fu_1078_p1 = result_reg_1423;

assign zext_ln378_fu_352_p1 = lshr_ln_fu_342_p4;

assign zext_ln379_fu_361_p1 = trunc_ln379_reg_1295;

assign zext_ln504_fu_503_p1 = Mx_zeros_fu_499_p1;

assign zext_ln505_fu_523_p1 = Mx_zeros_fu_499_p1;

assign zext_ln506_1_fu_816_p1 = select_ln506_fu_811_p3;

assign zext_ln506_fu_820_p1 = Mx_reg_1326;

endmodule //scatter_matrix_sin_or_cos_float_s
