// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module scatter_matrix_atan2_cordic_float_s (
        ap_clk,
        ap_rst,
        y_in,
        x_in,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] y_in;
input  [31:0] x_in;
output  [31:0] ap_return;
input   ap_ce;

reg   [31:0] c_reg_78;
reg   [31:0] c_reg_78_pp0_iter34_reg;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] c_reg_78_pp0_iter35_reg;
reg   [31:0] c_reg_78_pp0_iter36_reg;
wire   [31:0] grp_atan2_generic_float_s_fu_156_ap_return;
reg   [31:0] reg_177;
reg   [0:0] and_ln18_reg_560;
reg   [0:0] and_ln18_reg_560_pp0_iter25_reg;
reg   [0:0] and_ln18_1_reg_569;
reg   [0:0] and_ln18_1_reg_569_pp0_iter25_reg;
reg   [0:0] and_ln733_reg_577;
reg   [0:0] and_ln733_reg_577_pp0_iter25_reg;
reg   [0:0] icmp_ln733_reg_573;
reg   [0:0] icmp_ln733_reg_573_pp0_iter25_reg;
reg   [0:0] and_ln737_reg_585;
reg   [0:0] and_ln737_reg_585_pp0_iter25_reg;
reg   [0:0] icmp_ln737_reg_581;
reg   [0:0] icmp_ln737_reg_581_pp0_iter25_reg;
reg   [0:0] and_ln18_2_reg_589;
reg   [0:0] and_ln18_2_reg_589_pp0_iter25_reg;
reg   [0:0] and_ln18_3_reg_593;
reg   [0:0] and_ln18_3_reg_593_pp0_iter25_reg;
reg   [0:0] icmp_ln715_reg_611;
reg   [0:0] icmp_ln715_reg_611_pp0_iter25_reg;
reg   [0:0] and_ln717_1_reg_625;
reg   [0:0] and_ln717_1_reg_625_pp0_iter25_reg;
reg    ap_predicate_pred68_state28;
reg    ap_predicate_pred79_state28;
reg   [0:0] fpsx_sign_reg_538;
reg   [0:0] fpsx_sign_reg_538_pp0_iter1_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter2_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter3_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter4_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter5_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter6_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter7_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter8_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter9_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter10_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter11_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter12_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter13_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter14_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter15_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter16_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter17_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter18_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter19_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter20_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter21_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter22_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter23_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter24_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter25_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter26_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter27_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter28_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter29_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter30_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter31_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter32_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter33_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter34_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter35_reg;
reg   [0:0] fpsx_sign_reg_538_pp0_iter36_reg;
reg   [0:0] fpsy_sign_reg_543;
reg   [0:0] fpsy_sign_reg_543_pp0_iter1_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter2_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter3_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter4_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter5_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter6_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter7_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter8_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter9_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter10_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter11_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter12_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter13_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter14_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter15_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter16_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter17_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter18_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter19_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter20_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter21_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter22_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter23_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter24_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter25_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter26_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter27_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter28_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter29_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter30_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter31_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter32_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter33_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter34_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter35_reg;
reg   [0:0] fpsy_sign_reg_543_pp0_iter36_reg;
wire   [0:0] icmp_ln18_1_fu_241_p2;
reg   [0:0] icmp_ln18_1_reg_555;
wire   [0:0] and_ln18_fu_253_p2;
reg   [0:0] and_ln18_reg_560_pp0_iter1_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter2_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter3_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter4_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter5_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter6_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter7_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter8_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter9_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter10_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter11_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter12_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter13_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter14_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter15_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter16_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter17_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter18_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter19_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter20_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter21_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter22_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter23_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter24_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter26_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter27_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter28_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter29_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter30_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter31_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter32_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter33_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter34_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter35_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter36_reg;
reg   [0:0] and_ln18_reg_560_pp0_iter37_reg;
wire   [0:0] icmp_ln18_3_fu_265_p2;
reg   [0:0] icmp_ln18_3_reg_564;
wire   [0:0] and_ln18_1_fu_277_p2;
reg   [0:0] and_ln18_1_reg_569_pp0_iter1_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter2_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter3_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter4_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter5_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter6_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter7_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter8_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter9_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter10_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter11_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter12_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter13_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter14_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter15_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter16_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter17_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter18_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter19_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter20_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter21_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter22_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter23_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter24_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter26_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter27_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter28_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter29_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter30_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter31_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter32_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter33_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter34_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter35_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter36_reg;
reg   [0:0] and_ln18_1_reg_569_pp0_iter37_reg;
wire   [0:0] icmp_ln733_fu_283_p2;
reg   [0:0] icmp_ln733_reg_573_pp0_iter1_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter2_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter3_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter4_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter5_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter6_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter7_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter8_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter9_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter10_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter11_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter12_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter13_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter14_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter15_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter16_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter17_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter18_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter19_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter20_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter21_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter22_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter23_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter24_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter26_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter27_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter28_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter29_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter30_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter31_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter32_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter33_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter34_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter35_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter36_reg;
reg   [0:0] icmp_ln733_reg_573_pp0_iter37_reg;
wire   [0:0] and_ln733_fu_289_p2;
reg   [0:0] and_ln733_reg_577_pp0_iter1_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter2_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter3_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter4_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter5_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter6_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter7_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter8_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter9_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter10_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter11_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter12_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter13_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter14_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter15_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter16_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter17_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter18_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter19_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter20_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter21_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter22_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter23_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter24_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter26_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter27_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter28_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter29_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter30_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter31_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter32_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter33_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter34_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter35_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter36_reg;
reg   [0:0] and_ln733_reg_577_pp0_iter37_reg;
wire   [0:0] icmp_ln737_fu_295_p2;
reg   [0:0] icmp_ln737_reg_581_pp0_iter1_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter2_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter3_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter4_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter5_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter6_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter7_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter8_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter9_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter10_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter11_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter12_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter13_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter14_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter15_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter16_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter17_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter18_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter19_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter20_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter21_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter22_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter23_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter24_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter26_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter27_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter28_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter29_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter30_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter31_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter32_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter33_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter34_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter35_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter36_reg;
reg   [0:0] icmp_ln737_reg_581_pp0_iter37_reg;
wire   [0:0] and_ln737_fu_301_p2;
reg   [0:0] and_ln737_reg_585_pp0_iter1_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter2_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter3_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter4_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter5_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter6_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter7_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter8_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter9_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter10_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter11_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter12_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter13_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter14_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter15_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter16_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter17_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter18_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter19_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter20_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter21_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter22_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter23_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter24_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter26_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter27_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter28_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter29_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter30_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter31_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter32_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter33_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter34_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter35_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter36_reg;
reg   [0:0] and_ln737_reg_585_pp0_iter37_reg;
wire   [0:0] and_ln18_2_fu_307_p2;
reg   [0:0] and_ln18_2_reg_589_pp0_iter1_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter2_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter3_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter4_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter5_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter6_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter7_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter8_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter9_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter10_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter11_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter12_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter13_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter14_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter15_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter16_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter17_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter18_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter19_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter20_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter21_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter22_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter23_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter24_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter26_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter27_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter28_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter29_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter30_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter31_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter32_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter33_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter34_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter35_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter36_reg;
reg   [0:0] and_ln18_2_reg_589_pp0_iter37_reg;
wire   [0:0] and_ln18_3_fu_313_p2;
reg   [0:0] and_ln18_3_reg_593_pp0_iter1_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter2_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter3_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter4_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter5_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter6_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter7_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter8_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter9_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter10_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter11_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter12_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter13_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter14_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter15_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter16_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter17_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter18_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter19_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter20_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter21_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter22_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter23_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter24_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter26_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter27_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter28_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter29_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter30_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter31_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter32_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter33_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter34_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter35_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter36_reg;
reg   [0:0] and_ln18_3_reg_593_pp0_iter37_reg;
wire   [31:0] a_fu_331_p1;
reg   [31:0] a_reg_597;
reg   [31:0] a_reg_597_pp0_iter1_reg;
wire   [31:0] b_fu_348_p1;
reg   [31:0] b_reg_604;
reg   [31:0] b_reg_604_pp0_iter1_reg;
wire   [0:0] icmp_ln715_fu_353_p2;
reg   [0:0] icmp_ln715_reg_611_pp0_iter1_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter2_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter3_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter4_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter5_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter6_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter7_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter8_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter9_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter10_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter11_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter12_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter13_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter14_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter15_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter16_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter17_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter18_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter19_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter20_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter21_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter22_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter23_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter24_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter26_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter27_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter28_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter29_reg;
reg   [0:0] icmp_ln715_reg_611_pp0_iter30_reg;
wire   [0:0] icmp_ln717_fu_359_p2;
reg   [0:0] icmp_ln717_reg_615;
wire   [0:0] icmp_ln717_1_fu_365_p2;
reg   [0:0] icmp_ln717_1_reg_620;
wire   [0:0] and_ln717_1_fu_385_p2;
reg   [0:0] and_ln717_1_reg_625_pp0_iter2_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter3_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter4_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter5_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter6_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter7_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter8_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter9_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter10_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter11_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter12_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter13_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter14_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter15_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter16_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter17_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter18_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter19_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter20_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter21_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter22_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter23_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter24_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter26_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter27_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter28_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter29_reg;
reg   [0:0] and_ln717_1_reg_625_pp0_iter30_reg;
wire   [31:0] grp_fu_162_p2;
wire   [1:0] tmp_32_fu_391_p3;
reg   [1:0] tmp_32_reg_634;
wire   [31:0] grp_fu_167_p2;
reg   [31:0] d_reg_638;
wire   [31:0] bitcast_ln793_1_fu_427_p1;
wire   [31:0] select_ln780_fu_431_p3;
wire   [31:0] bitcast_ln327_28_fu_445_p1;
wire   [31:0] bitcast_ln327_27_fu_456_p1;
wire   [31:0] bitcast_ln327_26_fu_467_p1;
wire   [31:0] bitcast_ln327_25_fu_478_p1;
wire   [31:0] bitcast_ln327_24_fu_489_p1;
wire   [31:0] bitcast_ln327_fu_500_p1;
reg   [31:0] grp_atan2_generic_float_s_fu_156_y_in;
reg   [31:0] grp_atan2_generic_float_s_fu_156_x_in;
reg    grp_atan2_generic_float_s_fu_156_ap_ce;
reg    ap_predicate_op93_call_state3;
reg    ap_predicate_op94_call_state3;
wire    ap_block_pp0_stage0_11001_ignoreCallOp93;
wire   [31:0] ap_phi_reg_pp0_iter0_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter1_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter2_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter3_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter4_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter5_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter6_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter7_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter8_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter9_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter10_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter11_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter12_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter13_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter14_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter15_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter16_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter17_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter18_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter19_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter20_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter21_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter22_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter23_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter24_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter25_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter26_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter27_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter28_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter29_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter30_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter31_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter32_c_reg_78;
reg   [31:0] ap_phi_reg_pp0_iter33_c_reg_78;
reg    ap_predicate_pred1359_state33;
reg   [31:0] ap_phi_mux_UnifiedRetVal_phi_fu_104_p40;
wire   [31:0] ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter18_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter19_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter20_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter22_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter23_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter25_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter26_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter27_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter28_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter29_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter30_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter31_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter32_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter33_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter34_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter35_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter36_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter37_UnifiedRetVal_reg_92;
reg   [31:0] ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92;
wire   [31:0] bitcast_ln797_1_fu_533_p1;
reg    ap_predicate_pred1518_state38;
reg    ap_predicate_pred1542_state38;
reg    ap_predicate_pred1547_state38;
reg    ap_predicate_pred1552_state38;
wire    ap_block_pp0_stage0_ignoreCallOp93;
wire    ap_block_pp0_stage0_ignoreCallOp94;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_173_p0;
wire   [31:0] grp_fu_173_p1;
wire   [31:0] data_fu_183_p1;
wire   [31:0] data_25_fu_209_p1;
wire   [7:0] fpsy_exp_fu_221_p4;
wire   [22:0] fpsy_sig_fu_231_p1;
wire   [0:0] icmp_ln18_fu_235_p2;
wire   [0:0] xor_ln18_fu_247_p2;
wire   [7:0] fpsx_exp_fu_195_p4;
wire   [22:0] fpsx_sig_fu_205_p1;
wire   [0:0] icmp_ln18_2_fu_259_p2;
wire   [0:0] xor_ln18_1_fu_271_p2;
wire   [30:0] trunc_ln313_fu_319_p1;
wire   [31:0] t_31_fu_323_p3;
wire   [30:0] trunc_ln313_24_fu_336_p1;
wire   [31:0] t_32_fu_340_p3;
wire   [0:0] or_ln717_fu_371_p2;
wire   [0:0] or_ln717_1_fu_375_p2;
wire   [0:0] and_ln717_fu_379_p2;
wire   [0:0] grp_fu_173_p2;
wire   [31:0] bitcast_ln793_fu_397_p1;
wire   [0:0] bit_sel_fu_401_p3;
wire   [0:0] xor_ln793_fu_409_p2;
wire   [30:0] trunc_ln793_fu_415_p1;
wire   [31:0] xor_ln1_fu_419_p3;
wire   [31:0] t_30_fu_438_p3;
wire   [31:0] t_29_fu_449_p3;
wire   [31:0] t_28_fu_460_p3;
wire   [31:0] t_27_fu_471_p3;
wire   [31:0] t_26_fu_482_p3;
wire   [31:0] t_fu_493_p3;
wire   [31:0] bitcast_ln797_fu_504_p1;
wire   [0:0] bit_sel1_fu_507_p3;
wire   [0:0] xor_ln797_fu_515_p2;
wire   [30:0] trunc_ln797_fu_521_p1;
wire   [31:0] xor_ln_fu_525_p3;
reg    grp_fu_162_ce;
reg    grp_fu_167_ce;
reg    grp_fu_173_ce;
reg    ap_predicate_op82_fcmp_state1;
wire    ap_block_pp0_stage0_00001;
reg   [31:0] y_in_int_reg;
reg   [31:0] x_in_int_reg;
reg    ap_condition_1380;
reg    ap_condition_1455;
reg    ap_condition_1460;
reg    ap_condition_1465;
reg    ap_condition_1469;
reg    ap_condition_1476;
reg    ap_condition_1479;
reg    ap_condition_1482;
reg    ap_condition_1485;
reg    ap_condition_1512;
reg    ap_condition_1514;
reg    ap_condition_1516;
reg    ap_condition_1530;
reg    ap_condition_1533;
reg    ap_condition_1536;
wire    ap_ce_reg;

scatter_matrix_atan2_generic_float_s grp_atan2_generic_float_s_fu_156(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .y_in(grp_atan2_generic_float_s_fu_156_y_in),
    .x_in(grp_atan2_generic_float_s_fu_156_x_in),
    .ap_return(grp_atan2_generic_float_s_fu_156_ap_return),
    .ap_ce(grp_atan2_generic_float_s_fu_156_ap_ce)
);

scatter_matrix_fsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_5_full_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1070141403),
    .din1(reg_177),
    .ce(grp_fu_162_ce),
    .dout(grp_fu_162_p2)
);

scatter_matrix_fsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_5_full_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1078530011),
    .din1(ap_phi_reg_pp0_iter33_c_reg_78),
    .ce(grp_fu_167_ce),
    .dout(grp_fu_167_p2)
);

scatter_matrix_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_173_p0),
    .din1(grp_fu_173_p1),
    .ce(grp_fu_173_ce),
    .opcode(5'd2),
    .dout(grp_fu_173_p2)
);

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((1'd1 == and_ln18_1_fu_277_p2) | (1'd1 == and_ln18_fu_253_p2))) begin
            ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_92 <= 32'd2147483647;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_92;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_1380)) begin
            ap_phi_reg_pp0_iter1_c_reg_78 <= 32'd1061752795;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_c_reg_78 <= ap_phi_reg_pp0_iter0_c_reg_78;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_predicate_pred68_state28 == 1'b1)) begin
            ap_phi_reg_pp0_iter28_c_reg_78 <= grp_atan2_generic_float_s_fu_156_ap_return;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter28_c_reg_78 <= ap_phi_reg_pp0_iter27_c_reg_78;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_predicate_pred1359_state33 == 1'b1)) begin
            ap_phi_reg_pp0_iter33_c_reg_78 <= grp_fu_162_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter33_c_reg_78 <= ap_phi_reg_pp0_iter32_c_reg_78;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_predicate_pred1552_state38 == 1'b1)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= bitcast_ln327_28_fu_445_p1;
        end else if ((ap_predicate_pred1547_state38 == 1'b1)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= bitcast_ln327_27_fu_456_p1;
        end else if ((ap_predicate_pred1542_state38 == 1'b1)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= bitcast_ln327_26_fu_467_p1;
        end else if ((1'b1 == ap_condition_1536)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= bitcast_ln327_25_fu_478_p1;
        end else if ((1'b1 == ap_condition_1533)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= bitcast_ln327_24_fu_489_p1;
        end else if ((1'b1 == ap_condition_1530)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= bitcast_ln327_fu_500_p1;
        end else if ((ap_predicate_pred1518_state38 == 1'b1)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= select_ln780_fu_431_p3;
        end else if ((1'b1 == ap_condition_1516)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= grp_fu_167_p2;
        end else if ((1'b1 == ap_condition_1514)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= c_reg_78_pp0_iter36_reg;
        end else if ((1'b1 == ap_condition_1512)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= bitcast_ln793_1_fu_427_p1;
        end else if ((1'b1 == ap_condition_1485)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= 32'd0;
        end else if ((1'b1 == ap_condition_1482)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_1479)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= 32'd1078530011;
        end else if ((1'b1 == ap_condition_1476)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= 32'd3226013659;
        end else if ((1'b1 == ap_condition_1469)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= 32'd1061752795;
        end else if ((1'b1 == ap_condition_1465)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= 32'd3209236443;
        end else if ((1'b1 == ap_condition_1460)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= 32'd1075235812;
        end else if ((1'b1 == ap_condition_1455)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= 32'd3222719460;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter37_UnifiedRetVal_reg_92;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        a_reg_597[30 : 0] <= a_fu_331_p1[30 : 0];
        a_reg_597_pp0_iter1_reg[30 : 0] <= a_reg_597[30 : 0];
        and_ln18_1_reg_569 <= and_ln18_1_fu_277_p2;
        and_ln18_1_reg_569_pp0_iter10_reg <= and_ln18_1_reg_569_pp0_iter9_reg;
        and_ln18_1_reg_569_pp0_iter11_reg <= and_ln18_1_reg_569_pp0_iter10_reg;
        and_ln18_1_reg_569_pp0_iter12_reg <= and_ln18_1_reg_569_pp0_iter11_reg;
        and_ln18_1_reg_569_pp0_iter13_reg <= and_ln18_1_reg_569_pp0_iter12_reg;
        and_ln18_1_reg_569_pp0_iter14_reg <= and_ln18_1_reg_569_pp0_iter13_reg;
        and_ln18_1_reg_569_pp0_iter15_reg <= and_ln18_1_reg_569_pp0_iter14_reg;
        and_ln18_1_reg_569_pp0_iter16_reg <= and_ln18_1_reg_569_pp0_iter15_reg;
        and_ln18_1_reg_569_pp0_iter17_reg <= and_ln18_1_reg_569_pp0_iter16_reg;
        and_ln18_1_reg_569_pp0_iter18_reg <= and_ln18_1_reg_569_pp0_iter17_reg;
        and_ln18_1_reg_569_pp0_iter19_reg <= and_ln18_1_reg_569_pp0_iter18_reg;
        and_ln18_1_reg_569_pp0_iter1_reg <= and_ln18_1_reg_569;
        and_ln18_1_reg_569_pp0_iter20_reg <= and_ln18_1_reg_569_pp0_iter19_reg;
        and_ln18_1_reg_569_pp0_iter21_reg <= and_ln18_1_reg_569_pp0_iter20_reg;
        and_ln18_1_reg_569_pp0_iter22_reg <= and_ln18_1_reg_569_pp0_iter21_reg;
        and_ln18_1_reg_569_pp0_iter23_reg <= and_ln18_1_reg_569_pp0_iter22_reg;
        and_ln18_1_reg_569_pp0_iter24_reg <= and_ln18_1_reg_569_pp0_iter23_reg;
        and_ln18_1_reg_569_pp0_iter25_reg <= and_ln18_1_reg_569_pp0_iter24_reg;
        and_ln18_1_reg_569_pp0_iter26_reg <= and_ln18_1_reg_569_pp0_iter25_reg;
        and_ln18_1_reg_569_pp0_iter27_reg <= and_ln18_1_reg_569_pp0_iter26_reg;
        and_ln18_1_reg_569_pp0_iter28_reg <= and_ln18_1_reg_569_pp0_iter27_reg;
        and_ln18_1_reg_569_pp0_iter29_reg <= and_ln18_1_reg_569_pp0_iter28_reg;
        and_ln18_1_reg_569_pp0_iter2_reg <= and_ln18_1_reg_569_pp0_iter1_reg;
        and_ln18_1_reg_569_pp0_iter30_reg <= and_ln18_1_reg_569_pp0_iter29_reg;
        and_ln18_1_reg_569_pp0_iter31_reg <= and_ln18_1_reg_569_pp0_iter30_reg;
        and_ln18_1_reg_569_pp0_iter32_reg <= and_ln18_1_reg_569_pp0_iter31_reg;
        and_ln18_1_reg_569_pp0_iter33_reg <= and_ln18_1_reg_569_pp0_iter32_reg;
        and_ln18_1_reg_569_pp0_iter34_reg <= and_ln18_1_reg_569_pp0_iter33_reg;
        and_ln18_1_reg_569_pp0_iter35_reg <= and_ln18_1_reg_569_pp0_iter34_reg;
        and_ln18_1_reg_569_pp0_iter36_reg <= and_ln18_1_reg_569_pp0_iter35_reg;
        and_ln18_1_reg_569_pp0_iter37_reg <= and_ln18_1_reg_569_pp0_iter36_reg;
        and_ln18_1_reg_569_pp0_iter3_reg <= and_ln18_1_reg_569_pp0_iter2_reg;
        and_ln18_1_reg_569_pp0_iter4_reg <= and_ln18_1_reg_569_pp0_iter3_reg;
        and_ln18_1_reg_569_pp0_iter5_reg <= and_ln18_1_reg_569_pp0_iter4_reg;
        and_ln18_1_reg_569_pp0_iter6_reg <= and_ln18_1_reg_569_pp0_iter5_reg;
        and_ln18_1_reg_569_pp0_iter7_reg <= and_ln18_1_reg_569_pp0_iter6_reg;
        and_ln18_1_reg_569_pp0_iter8_reg <= and_ln18_1_reg_569_pp0_iter7_reg;
        and_ln18_1_reg_569_pp0_iter9_reg <= and_ln18_1_reg_569_pp0_iter8_reg;
        and_ln18_2_reg_589 <= and_ln18_2_fu_307_p2;
        and_ln18_2_reg_589_pp0_iter10_reg <= and_ln18_2_reg_589_pp0_iter9_reg;
        and_ln18_2_reg_589_pp0_iter11_reg <= and_ln18_2_reg_589_pp0_iter10_reg;
        and_ln18_2_reg_589_pp0_iter12_reg <= and_ln18_2_reg_589_pp0_iter11_reg;
        and_ln18_2_reg_589_pp0_iter13_reg <= and_ln18_2_reg_589_pp0_iter12_reg;
        and_ln18_2_reg_589_pp0_iter14_reg <= and_ln18_2_reg_589_pp0_iter13_reg;
        and_ln18_2_reg_589_pp0_iter15_reg <= and_ln18_2_reg_589_pp0_iter14_reg;
        and_ln18_2_reg_589_pp0_iter16_reg <= and_ln18_2_reg_589_pp0_iter15_reg;
        and_ln18_2_reg_589_pp0_iter17_reg <= and_ln18_2_reg_589_pp0_iter16_reg;
        and_ln18_2_reg_589_pp0_iter18_reg <= and_ln18_2_reg_589_pp0_iter17_reg;
        and_ln18_2_reg_589_pp0_iter19_reg <= and_ln18_2_reg_589_pp0_iter18_reg;
        and_ln18_2_reg_589_pp0_iter1_reg <= and_ln18_2_reg_589;
        and_ln18_2_reg_589_pp0_iter20_reg <= and_ln18_2_reg_589_pp0_iter19_reg;
        and_ln18_2_reg_589_pp0_iter21_reg <= and_ln18_2_reg_589_pp0_iter20_reg;
        and_ln18_2_reg_589_pp0_iter22_reg <= and_ln18_2_reg_589_pp0_iter21_reg;
        and_ln18_2_reg_589_pp0_iter23_reg <= and_ln18_2_reg_589_pp0_iter22_reg;
        and_ln18_2_reg_589_pp0_iter24_reg <= and_ln18_2_reg_589_pp0_iter23_reg;
        and_ln18_2_reg_589_pp0_iter25_reg <= and_ln18_2_reg_589_pp0_iter24_reg;
        and_ln18_2_reg_589_pp0_iter26_reg <= and_ln18_2_reg_589_pp0_iter25_reg;
        and_ln18_2_reg_589_pp0_iter27_reg <= and_ln18_2_reg_589_pp0_iter26_reg;
        and_ln18_2_reg_589_pp0_iter28_reg <= and_ln18_2_reg_589_pp0_iter27_reg;
        and_ln18_2_reg_589_pp0_iter29_reg <= and_ln18_2_reg_589_pp0_iter28_reg;
        and_ln18_2_reg_589_pp0_iter2_reg <= and_ln18_2_reg_589_pp0_iter1_reg;
        and_ln18_2_reg_589_pp0_iter30_reg <= and_ln18_2_reg_589_pp0_iter29_reg;
        and_ln18_2_reg_589_pp0_iter31_reg <= and_ln18_2_reg_589_pp0_iter30_reg;
        and_ln18_2_reg_589_pp0_iter32_reg <= and_ln18_2_reg_589_pp0_iter31_reg;
        and_ln18_2_reg_589_pp0_iter33_reg <= and_ln18_2_reg_589_pp0_iter32_reg;
        and_ln18_2_reg_589_pp0_iter34_reg <= and_ln18_2_reg_589_pp0_iter33_reg;
        and_ln18_2_reg_589_pp0_iter35_reg <= and_ln18_2_reg_589_pp0_iter34_reg;
        and_ln18_2_reg_589_pp0_iter36_reg <= and_ln18_2_reg_589_pp0_iter35_reg;
        and_ln18_2_reg_589_pp0_iter37_reg <= and_ln18_2_reg_589_pp0_iter36_reg;
        and_ln18_2_reg_589_pp0_iter3_reg <= and_ln18_2_reg_589_pp0_iter2_reg;
        and_ln18_2_reg_589_pp0_iter4_reg <= and_ln18_2_reg_589_pp0_iter3_reg;
        and_ln18_2_reg_589_pp0_iter5_reg <= and_ln18_2_reg_589_pp0_iter4_reg;
        and_ln18_2_reg_589_pp0_iter6_reg <= and_ln18_2_reg_589_pp0_iter5_reg;
        and_ln18_2_reg_589_pp0_iter7_reg <= and_ln18_2_reg_589_pp0_iter6_reg;
        and_ln18_2_reg_589_pp0_iter8_reg <= and_ln18_2_reg_589_pp0_iter7_reg;
        and_ln18_2_reg_589_pp0_iter9_reg <= and_ln18_2_reg_589_pp0_iter8_reg;
        and_ln18_3_reg_593 <= and_ln18_3_fu_313_p2;
        and_ln18_3_reg_593_pp0_iter10_reg <= and_ln18_3_reg_593_pp0_iter9_reg;
        and_ln18_3_reg_593_pp0_iter11_reg <= and_ln18_3_reg_593_pp0_iter10_reg;
        and_ln18_3_reg_593_pp0_iter12_reg <= and_ln18_3_reg_593_pp0_iter11_reg;
        and_ln18_3_reg_593_pp0_iter13_reg <= and_ln18_3_reg_593_pp0_iter12_reg;
        and_ln18_3_reg_593_pp0_iter14_reg <= and_ln18_3_reg_593_pp0_iter13_reg;
        and_ln18_3_reg_593_pp0_iter15_reg <= and_ln18_3_reg_593_pp0_iter14_reg;
        and_ln18_3_reg_593_pp0_iter16_reg <= and_ln18_3_reg_593_pp0_iter15_reg;
        and_ln18_3_reg_593_pp0_iter17_reg <= and_ln18_3_reg_593_pp0_iter16_reg;
        and_ln18_3_reg_593_pp0_iter18_reg <= and_ln18_3_reg_593_pp0_iter17_reg;
        and_ln18_3_reg_593_pp0_iter19_reg <= and_ln18_3_reg_593_pp0_iter18_reg;
        and_ln18_3_reg_593_pp0_iter1_reg <= and_ln18_3_reg_593;
        and_ln18_3_reg_593_pp0_iter20_reg <= and_ln18_3_reg_593_pp0_iter19_reg;
        and_ln18_3_reg_593_pp0_iter21_reg <= and_ln18_3_reg_593_pp0_iter20_reg;
        and_ln18_3_reg_593_pp0_iter22_reg <= and_ln18_3_reg_593_pp0_iter21_reg;
        and_ln18_3_reg_593_pp0_iter23_reg <= and_ln18_3_reg_593_pp0_iter22_reg;
        and_ln18_3_reg_593_pp0_iter24_reg <= and_ln18_3_reg_593_pp0_iter23_reg;
        and_ln18_3_reg_593_pp0_iter25_reg <= and_ln18_3_reg_593_pp0_iter24_reg;
        and_ln18_3_reg_593_pp0_iter26_reg <= and_ln18_3_reg_593_pp0_iter25_reg;
        and_ln18_3_reg_593_pp0_iter27_reg <= and_ln18_3_reg_593_pp0_iter26_reg;
        and_ln18_3_reg_593_pp0_iter28_reg <= and_ln18_3_reg_593_pp0_iter27_reg;
        and_ln18_3_reg_593_pp0_iter29_reg <= and_ln18_3_reg_593_pp0_iter28_reg;
        and_ln18_3_reg_593_pp0_iter2_reg <= and_ln18_3_reg_593_pp0_iter1_reg;
        and_ln18_3_reg_593_pp0_iter30_reg <= and_ln18_3_reg_593_pp0_iter29_reg;
        and_ln18_3_reg_593_pp0_iter31_reg <= and_ln18_3_reg_593_pp0_iter30_reg;
        and_ln18_3_reg_593_pp0_iter32_reg <= and_ln18_3_reg_593_pp0_iter31_reg;
        and_ln18_3_reg_593_pp0_iter33_reg <= and_ln18_3_reg_593_pp0_iter32_reg;
        and_ln18_3_reg_593_pp0_iter34_reg <= and_ln18_3_reg_593_pp0_iter33_reg;
        and_ln18_3_reg_593_pp0_iter35_reg <= and_ln18_3_reg_593_pp0_iter34_reg;
        and_ln18_3_reg_593_pp0_iter36_reg <= and_ln18_3_reg_593_pp0_iter35_reg;
        and_ln18_3_reg_593_pp0_iter37_reg <= and_ln18_3_reg_593_pp0_iter36_reg;
        and_ln18_3_reg_593_pp0_iter3_reg <= and_ln18_3_reg_593_pp0_iter2_reg;
        and_ln18_3_reg_593_pp0_iter4_reg <= and_ln18_3_reg_593_pp0_iter3_reg;
        and_ln18_3_reg_593_pp0_iter5_reg <= and_ln18_3_reg_593_pp0_iter4_reg;
        and_ln18_3_reg_593_pp0_iter6_reg <= and_ln18_3_reg_593_pp0_iter5_reg;
        and_ln18_3_reg_593_pp0_iter7_reg <= and_ln18_3_reg_593_pp0_iter6_reg;
        and_ln18_3_reg_593_pp0_iter8_reg <= and_ln18_3_reg_593_pp0_iter7_reg;
        and_ln18_3_reg_593_pp0_iter9_reg <= and_ln18_3_reg_593_pp0_iter8_reg;
        and_ln18_reg_560 <= and_ln18_fu_253_p2;
        and_ln18_reg_560_pp0_iter10_reg <= and_ln18_reg_560_pp0_iter9_reg;
        and_ln18_reg_560_pp0_iter11_reg <= and_ln18_reg_560_pp0_iter10_reg;
        and_ln18_reg_560_pp0_iter12_reg <= and_ln18_reg_560_pp0_iter11_reg;
        and_ln18_reg_560_pp0_iter13_reg <= and_ln18_reg_560_pp0_iter12_reg;
        and_ln18_reg_560_pp0_iter14_reg <= and_ln18_reg_560_pp0_iter13_reg;
        and_ln18_reg_560_pp0_iter15_reg <= and_ln18_reg_560_pp0_iter14_reg;
        and_ln18_reg_560_pp0_iter16_reg <= and_ln18_reg_560_pp0_iter15_reg;
        and_ln18_reg_560_pp0_iter17_reg <= and_ln18_reg_560_pp0_iter16_reg;
        and_ln18_reg_560_pp0_iter18_reg <= and_ln18_reg_560_pp0_iter17_reg;
        and_ln18_reg_560_pp0_iter19_reg <= and_ln18_reg_560_pp0_iter18_reg;
        and_ln18_reg_560_pp0_iter1_reg <= and_ln18_reg_560;
        and_ln18_reg_560_pp0_iter20_reg <= and_ln18_reg_560_pp0_iter19_reg;
        and_ln18_reg_560_pp0_iter21_reg <= and_ln18_reg_560_pp0_iter20_reg;
        and_ln18_reg_560_pp0_iter22_reg <= and_ln18_reg_560_pp0_iter21_reg;
        and_ln18_reg_560_pp0_iter23_reg <= and_ln18_reg_560_pp0_iter22_reg;
        and_ln18_reg_560_pp0_iter24_reg <= and_ln18_reg_560_pp0_iter23_reg;
        and_ln18_reg_560_pp0_iter25_reg <= and_ln18_reg_560_pp0_iter24_reg;
        and_ln18_reg_560_pp0_iter26_reg <= and_ln18_reg_560_pp0_iter25_reg;
        and_ln18_reg_560_pp0_iter27_reg <= and_ln18_reg_560_pp0_iter26_reg;
        and_ln18_reg_560_pp0_iter28_reg <= and_ln18_reg_560_pp0_iter27_reg;
        and_ln18_reg_560_pp0_iter29_reg <= and_ln18_reg_560_pp0_iter28_reg;
        and_ln18_reg_560_pp0_iter2_reg <= and_ln18_reg_560_pp0_iter1_reg;
        and_ln18_reg_560_pp0_iter30_reg <= and_ln18_reg_560_pp0_iter29_reg;
        and_ln18_reg_560_pp0_iter31_reg <= and_ln18_reg_560_pp0_iter30_reg;
        and_ln18_reg_560_pp0_iter32_reg <= and_ln18_reg_560_pp0_iter31_reg;
        and_ln18_reg_560_pp0_iter33_reg <= and_ln18_reg_560_pp0_iter32_reg;
        and_ln18_reg_560_pp0_iter34_reg <= and_ln18_reg_560_pp0_iter33_reg;
        and_ln18_reg_560_pp0_iter35_reg <= and_ln18_reg_560_pp0_iter34_reg;
        and_ln18_reg_560_pp0_iter36_reg <= and_ln18_reg_560_pp0_iter35_reg;
        and_ln18_reg_560_pp0_iter37_reg <= and_ln18_reg_560_pp0_iter36_reg;
        and_ln18_reg_560_pp0_iter3_reg <= and_ln18_reg_560_pp0_iter2_reg;
        and_ln18_reg_560_pp0_iter4_reg <= and_ln18_reg_560_pp0_iter3_reg;
        and_ln18_reg_560_pp0_iter5_reg <= and_ln18_reg_560_pp0_iter4_reg;
        and_ln18_reg_560_pp0_iter6_reg <= and_ln18_reg_560_pp0_iter5_reg;
        and_ln18_reg_560_pp0_iter7_reg <= and_ln18_reg_560_pp0_iter6_reg;
        and_ln18_reg_560_pp0_iter8_reg <= and_ln18_reg_560_pp0_iter7_reg;
        and_ln18_reg_560_pp0_iter9_reg <= and_ln18_reg_560_pp0_iter8_reg;
        and_ln717_1_reg_625 <= and_ln717_1_fu_385_p2;
        and_ln717_1_reg_625_pp0_iter10_reg <= and_ln717_1_reg_625_pp0_iter9_reg;
        and_ln717_1_reg_625_pp0_iter11_reg <= and_ln717_1_reg_625_pp0_iter10_reg;
        and_ln717_1_reg_625_pp0_iter12_reg <= and_ln717_1_reg_625_pp0_iter11_reg;
        and_ln717_1_reg_625_pp0_iter13_reg <= and_ln717_1_reg_625_pp0_iter12_reg;
        and_ln717_1_reg_625_pp0_iter14_reg <= and_ln717_1_reg_625_pp0_iter13_reg;
        and_ln717_1_reg_625_pp0_iter15_reg <= and_ln717_1_reg_625_pp0_iter14_reg;
        and_ln717_1_reg_625_pp0_iter16_reg <= and_ln717_1_reg_625_pp0_iter15_reg;
        and_ln717_1_reg_625_pp0_iter17_reg <= and_ln717_1_reg_625_pp0_iter16_reg;
        and_ln717_1_reg_625_pp0_iter18_reg <= and_ln717_1_reg_625_pp0_iter17_reg;
        and_ln717_1_reg_625_pp0_iter19_reg <= and_ln717_1_reg_625_pp0_iter18_reg;
        and_ln717_1_reg_625_pp0_iter20_reg <= and_ln717_1_reg_625_pp0_iter19_reg;
        and_ln717_1_reg_625_pp0_iter21_reg <= and_ln717_1_reg_625_pp0_iter20_reg;
        and_ln717_1_reg_625_pp0_iter22_reg <= and_ln717_1_reg_625_pp0_iter21_reg;
        and_ln717_1_reg_625_pp0_iter23_reg <= and_ln717_1_reg_625_pp0_iter22_reg;
        and_ln717_1_reg_625_pp0_iter24_reg <= and_ln717_1_reg_625_pp0_iter23_reg;
        and_ln717_1_reg_625_pp0_iter25_reg <= and_ln717_1_reg_625_pp0_iter24_reg;
        and_ln717_1_reg_625_pp0_iter26_reg <= and_ln717_1_reg_625_pp0_iter25_reg;
        and_ln717_1_reg_625_pp0_iter27_reg <= and_ln717_1_reg_625_pp0_iter26_reg;
        and_ln717_1_reg_625_pp0_iter28_reg <= and_ln717_1_reg_625_pp0_iter27_reg;
        and_ln717_1_reg_625_pp0_iter29_reg <= and_ln717_1_reg_625_pp0_iter28_reg;
        and_ln717_1_reg_625_pp0_iter2_reg <= and_ln717_1_reg_625;
        and_ln717_1_reg_625_pp0_iter30_reg <= and_ln717_1_reg_625_pp0_iter29_reg;
        and_ln717_1_reg_625_pp0_iter3_reg <= and_ln717_1_reg_625_pp0_iter2_reg;
        and_ln717_1_reg_625_pp0_iter4_reg <= and_ln717_1_reg_625_pp0_iter3_reg;
        and_ln717_1_reg_625_pp0_iter5_reg <= and_ln717_1_reg_625_pp0_iter4_reg;
        and_ln717_1_reg_625_pp0_iter6_reg <= and_ln717_1_reg_625_pp0_iter5_reg;
        and_ln717_1_reg_625_pp0_iter7_reg <= and_ln717_1_reg_625_pp0_iter6_reg;
        and_ln717_1_reg_625_pp0_iter8_reg <= and_ln717_1_reg_625_pp0_iter7_reg;
        and_ln717_1_reg_625_pp0_iter9_reg <= and_ln717_1_reg_625_pp0_iter8_reg;
        and_ln733_reg_577 <= and_ln733_fu_289_p2;
        and_ln733_reg_577_pp0_iter10_reg <= and_ln733_reg_577_pp0_iter9_reg;
        and_ln733_reg_577_pp0_iter11_reg <= and_ln733_reg_577_pp0_iter10_reg;
        and_ln733_reg_577_pp0_iter12_reg <= and_ln733_reg_577_pp0_iter11_reg;
        and_ln733_reg_577_pp0_iter13_reg <= and_ln733_reg_577_pp0_iter12_reg;
        and_ln733_reg_577_pp0_iter14_reg <= and_ln733_reg_577_pp0_iter13_reg;
        and_ln733_reg_577_pp0_iter15_reg <= and_ln733_reg_577_pp0_iter14_reg;
        and_ln733_reg_577_pp0_iter16_reg <= and_ln733_reg_577_pp0_iter15_reg;
        and_ln733_reg_577_pp0_iter17_reg <= and_ln733_reg_577_pp0_iter16_reg;
        and_ln733_reg_577_pp0_iter18_reg <= and_ln733_reg_577_pp0_iter17_reg;
        and_ln733_reg_577_pp0_iter19_reg <= and_ln733_reg_577_pp0_iter18_reg;
        and_ln733_reg_577_pp0_iter1_reg <= and_ln733_reg_577;
        and_ln733_reg_577_pp0_iter20_reg <= and_ln733_reg_577_pp0_iter19_reg;
        and_ln733_reg_577_pp0_iter21_reg <= and_ln733_reg_577_pp0_iter20_reg;
        and_ln733_reg_577_pp0_iter22_reg <= and_ln733_reg_577_pp0_iter21_reg;
        and_ln733_reg_577_pp0_iter23_reg <= and_ln733_reg_577_pp0_iter22_reg;
        and_ln733_reg_577_pp0_iter24_reg <= and_ln733_reg_577_pp0_iter23_reg;
        and_ln733_reg_577_pp0_iter25_reg <= and_ln733_reg_577_pp0_iter24_reg;
        and_ln733_reg_577_pp0_iter26_reg <= and_ln733_reg_577_pp0_iter25_reg;
        and_ln733_reg_577_pp0_iter27_reg <= and_ln733_reg_577_pp0_iter26_reg;
        and_ln733_reg_577_pp0_iter28_reg <= and_ln733_reg_577_pp0_iter27_reg;
        and_ln733_reg_577_pp0_iter29_reg <= and_ln733_reg_577_pp0_iter28_reg;
        and_ln733_reg_577_pp0_iter2_reg <= and_ln733_reg_577_pp0_iter1_reg;
        and_ln733_reg_577_pp0_iter30_reg <= and_ln733_reg_577_pp0_iter29_reg;
        and_ln733_reg_577_pp0_iter31_reg <= and_ln733_reg_577_pp0_iter30_reg;
        and_ln733_reg_577_pp0_iter32_reg <= and_ln733_reg_577_pp0_iter31_reg;
        and_ln733_reg_577_pp0_iter33_reg <= and_ln733_reg_577_pp0_iter32_reg;
        and_ln733_reg_577_pp0_iter34_reg <= and_ln733_reg_577_pp0_iter33_reg;
        and_ln733_reg_577_pp0_iter35_reg <= and_ln733_reg_577_pp0_iter34_reg;
        and_ln733_reg_577_pp0_iter36_reg <= and_ln733_reg_577_pp0_iter35_reg;
        and_ln733_reg_577_pp0_iter37_reg <= and_ln733_reg_577_pp0_iter36_reg;
        and_ln733_reg_577_pp0_iter3_reg <= and_ln733_reg_577_pp0_iter2_reg;
        and_ln733_reg_577_pp0_iter4_reg <= and_ln733_reg_577_pp0_iter3_reg;
        and_ln733_reg_577_pp0_iter5_reg <= and_ln733_reg_577_pp0_iter4_reg;
        and_ln733_reg_577_pp0_iter6_reg <= and_ln733_reg_577_pp0_iter5_reg;
        and_ln733_reg_577_pp0_iter7_reg <= and_ln733_reg_577_pp0_iter6_reg;
        and_ln733_reg_577_pp0_iter8_reg <= and_ln733_reg_577_pp0_iter7_reg;
        and_ln733_reg_577_pp0_iter9_reg <= and_ln733_reg_577_pp0_iter8_reg;
        and_ln737_reg_585 <= and_ln737_fu_301_p2;
        and_ln737_reg_585_pp0_iter10_reg <= and_ln737_reg_585_pp0_iter9_reg;
        and_ln737_reg_585_pp0_iter11_reg <= and_ln737_reg_585_pp0_iter10_reg;
        and_ln737_reg_585_pp0_iter12_reg <= and_ln737_reg_585_pp0_iter11_reg;
        and_ln737_reg_585_pp0_iter13_reg <= and_ln737_reg_585_pp0_iter12_reg;
        and_ln737_reg_585_pp0_iter14_reg <= and_ln737_reg_585_pp0_iter13_reg;
        and_ln737_reg_585_pp0_iter15_reg <= and_ln737_reg_585_pp0_iter14_reg;
        and_ln737_reg_585_pp0_iter16_reg <= and_ln737_reg_585_pp0_iter15_reg;
        and_ln737_reg_585_pp0_iter17_reg <= and_ln737_reg_585_pp0_iter16_reg;
        and_ln737_reg_585_pp0_iter18_reg <= and_ln737_reg_585_pp0_iter17_reg;
        and_ln737_reg_585_pp0_iter19_reg <= and_ln737_reg_585_pp0_iter18_reg;
        and_ln737_reg_585_pp0_iter1_reg <= and_ln737_reg_585;
        and_ln737_reg_585_pp0_iter20_reg <= and_ln737_reg_585_pp0_iter19_reg;
        and_ln737_reg_585_pp0_iter21_reg <= and_ln737_reg_585_pp0_iter20_reg;
        and_ln737_reg_585_pp0_iter22_reg <= and_ln737_reg_585_pp0_iter21_reg;
        and_ln737_reg_585_pp0_iter23_reg <= and_ln737_reg_585_pp0_iter22_reg;
        and_ln737_reg_585_pp0_iter24_reg <= and_ln737_reg_585_pp0_iter23_reg;
        and_ln737_reg_585_pp0_iter25_reg <= and_ln737_reg_585_pp0_iter24_reg;
        and_ln737_reg_585_pp0_iter26_reg <= and_ln737_reg_585_pp0_iter25_reg;
        and_ln737_reg_585_pp0_iter27_reg <= and_ln737_reg_585_pp0_iter26_reg;
        and_ln737_reg_585_pp0_iter28_reg <= and_ln737_reg_585_pp0_iter27_reg;
        and_ln737_reg_585_pp0_iter29_reg <= and_ln737_reg_585_pp0_iter28_reg;
        and_ln737_reg_585_pp0_iter2_reg <= and_ln737_reg_585_pp0_iter1_reg;
        and_ln737_reg_585_pp0_iter30_reg <= and_ln737_reg_585_pp0_iter29_reg;
        and_ln737_reg_585_pp0_iter31_reg <= and_ln737_reg_585_pp0_iter30_reg;
        and_ln737_reg_585_pp0_iter32_reg <= and_ln737_reg_585_pp0_iter31_reg;
        and_ln737_reg_585_pp0_iter33_reg <= and_ln737_reg_585_pp0_iter32_reg;
        and_ln737_reg_585_pp0_iter34_reg <= and_ln737_reg_585_pp0_iter33_reg;
        and_ln737_reg_585_pp0_iter35_reg <= and_ln737_reg_585_pp0_iter34_reg;
        and_ln737_reg_585_pp0_iter36_reg <= and_ln737_reg_585_pp0_iter35_reg;
        and_ln737_reg_585_pp0_iter37_reg <= and_ln737_reg_585_pp0_iter36_reg;
        and_ln737_reg_585_pp0_iter3_reg <= and_ln737_reg_585_pp0_iter2_reg;
        and_ln737_reg_585_pp0_iter4_reg <= and_ln737_reg_585_pp0_iter3_reg;
        and_ln737_reg_585_pp0_iter5_reg <= and_ln737_reg_585_pp0_iter4_reg;
        and_ln737_reg_585_pp0_iter6_reg <= and_ln737_reg_585_pp0_iter5_reg;
        and_ln737_reg_585_pp0_iter7_reg <= and_ln737_reg_585_pp0_iter6_reg;
        and_ln737_reg_585_pp0_iter8_reg <= and_ln737_reg_585_pp0_iter7_reg;
        and_ln737_reg_585_pp0_iter9_reg <= and_ln737_reg_585_pp0_iter8_reg;
        ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter10_c_reg_78 <= ap_phi_reg_pp0_iter9_c_reg_78;
        ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter11_c_reg_78 <= ap_phi_reg_pp0_iter10_c_reg_78;
        ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter12_c_reg_78 <= ap_phi_reg_pp0_iter11_c_reg_78;
        ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter13_c_reg_78 <= ap_phi_reg_pp0_iter12_c_reg_78;
        ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter14_c_reg_78 <= ap_phi_reg_pp0_iter13_c_reg_78;
        ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter15_c_reg_78 <= ap_phi_reg_pp0_iter14_c_reg_78;
        ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter16_c_reg_78 <= ap_phi_reg_pp0_iter15_c_reg_78;
        ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter17_c_reg_78 <= ap_phi_reg_pp0_iter16_c_reg_78;
        ap_phi_reg_pp0_iter18_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter18_c_reg_78 <= ap_phi_reg_pp0_iter17_c_reg_78;
        ap_phi_reg_pp0_iter19_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter18_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter19_c_reg_78 <= ap_phi_reg_pp0_iter18_c_reg_78;
        ap_phi_reg_pp0_iter20_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter19_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter20_c_reg_78 <= ap_phi_reg_pp0_iter19_c_reg_78;
        ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter20_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter21_c_reg_78 <= ap_phi_reg_pp0_iter20_c_reg_78;
        ap_phi_reg_pp0_iter22_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter22_c_reg_78 <= ap_phi_reg_pp0_iter21_c_reg_78;
        ap_phi_reg_pp0_iter23_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter22_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter23_c_reg_78 <= ap_phi_reg_pp0_iter22_c_reg_78;
        ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter23_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter24_c_reg_78 <= ap_phi_reg_pp0_iter23_c_reg_78;
        ap_phi_reg_pp0_iter25_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter25_c_reg_78 <= ap_phi_reg_pp0_iter24_c_reg_78;
        ap_phi_reg_pp0_iter26_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter25_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter26_c_reg_78 <= ap_phi_reg_pp0_iter25_c_reg_78;
        ap_phi_reg_pp0_iter27_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter26_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter27_c_reg_78 <= ap_phi_reg_pp0_iter26_c_reg_78;
        ap_phi_reg_pp0_iter28_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter27_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter29_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter28_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter29_c_reg_78 <= ap_phi_reg_pp0_iter28_c_reg_78;
        ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter2_c_reg_78 <= ap_phi_reg_pp0_iter1_c_reg_78;
        ap_phi_reg_pp0_iter30_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter29_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter30_c_reg_78 <= ap_phi_reg_pp0_iter29_c_reg_78;
        ap_phi_reg_pp0_iter31_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter30_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter31_c_reg_78 <= ap_phi_reg_pp0_iter30_c_reg_78;
        ap_phi_reg_pp0_iter32_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter31_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter32_c_reg_78 <= ap_phi_reg_pp0_iter31_c_reg_78;
        ap_phi_reg_pp0_iter33_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter32_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter34_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter33_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter35_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter34_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter36_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter35_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter37_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter36_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter3_c_reg_78 <= ap_phi_reg_pp0_iter2_c_reg_78;
        ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter4_c_reg_78 <= ap_phi_reg_pp0_iter3_c_reg_78;
        ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter5_c_reg_78 <= ap_phi_reg_pp0_iter4_c_reg_78;
        ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter6_c_reg_78 <= ap_phi_reg_pp0_iter5_c_reg_78;
        ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter7_c_reg_78 <= ap_phi_reg_pp0_iter6_c_reg_78;
        ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter8_c_reg_78 <= ap_phi_reg_pp0_iter7_c_reg_78;
        ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_92 <= ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_92;
        ap_phi_reg_pp0_iter9_c_reg_78 <= ap_phi_reg_pp0_iter8_c_reg_78;
        ap_predicate_pred1359_state33 <= ((1'd1 == and_ln717_1_reg_625_pp0_iter30_reg) & (icmp_ln715_reg_611_pp0_iter30_reg == 1'd0) & (icmp_ln737_reg_581_pp0_iter30_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter30_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter30_reg) & (1'd0 == and_ln737_reg_585_pp0_iter30_reg) & (1'd0 == and_ln733_reg_577_pp0_iter30_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter30_reg) & (1'd0 == and_ln18_reg_560_pp0_iter30_reg) & (icmp_ln733_reg_573_pp0_iter30_reg == 1'd0));
        ap_predicate_pred1518_state38 <= ((1'd1 == and_ln18_3_reg_593_pp0_iter35_reg) & (icmp_ln737_reg_581_pp0_iter35_reg == 1'd0) & (1'd0 == and_ln18_2_reg_589_pp0_iter35_reg) & (1'd0 == and_ln737_reg_585_pp0_iter35_reg) & (1'd0 == and_ln733_reg_577_pp0_iter35_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter35_reg) & (1'd0 == and_ln18_reg_560_pp0_iter35_reg) & (icmp_ln733_reg_573_pp0_iter35_reg == 1'd0));
        ap_predicate_pred1542_state38 <= ((1'd0 == and_ln737_reg_585_pp0_iter35_reg) & (1'd0 == and_ln733_reg_577_pp0_iter35_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter35_reg) & (1'd0 == and_ln18_reg_560_pp0_iter35_reg) & (icmp_ln733_reg_573_pp0_iter35_reg == 1'd1) & (fpsx_sign_reg_538_pp0_iter35_reg == 1'd1));
        ap_predicate_pred1547_state38 <= ((1'd0 == and_ln737_reg_585_pp0_iter35_reg) & (1'd0 == and_ln733_reg_577_pp0_iter35_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter35_reg) & (1'd0 == and_ln18_reg_560_pp0_iter35_reg) & (icmp_ln733_reg_573_pp0_iter35_reg == 1'd1) & (fpsx_sign_reg_538_pp0_iter35_reg == 1'd0));
        ap_predicate_pred1552_state38 <= ((icmp_ln737_reg_581_pp0_iter35_reg == 1'd1) & (1'd0 == and_ln737_reg_585_pp0_iter35_reg) & (1'd0 == and_ln733_reg_577_pp0_iter35_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter35_reg) & (1'd0 == and_ln18_reg_560_pp0_iter35_reg) & (icmp_ln733_reg_573_pp0_iter35_reg == 1'd0));
        ap_predicate_pred68_state28 <= ((icmp_ln715_reg_611_pp0_iter25_reg == 1'd0) & (icmp_ln737_reg_581_pp0_iter25_reg == 1'd0) & (icmp_ln733_reg_573_pp0_iter25_reg == 1'd0) & (1'd0 == and_ln717_1_reg_625_pp0_iter25_reg) & (1'd0 == and_ln18_3_reg_593_pp0_iter25_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter25_reg) & (1'd0 == and_ln737_reg_585_pp0_iter25_reg) & (1'd0 == and_ln733_reg_577_pp0_iter25_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter25_reg) & (1'd0 == and_ln18_reg_560_pp0_iter25_reg));
        ap_predicate_pred79_state28 <= ((1'd1 == and_ln717_1_reg_625_pp0_iter25_reg) & (icmp_ln715_reg_611_pp0_iter25_reg == 1'd0) & (icmp_ln737_reg_581_pp0_iter25_reg == 1'd0) & (icmp_ln733_reg_573_pp0_iter25_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter25_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter25_reg) & (1'd0 == and_ln737_reg_585_pp0_iter25_reg) & (1'd0 == and_ln733_reg_577_pp0_iter25_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter25_reg) & (1'd0 == and_ln18_reg_560_pp0_iter25_reg));
        b_reg_604[30 : 0] <= b_fu_348_p1[30 : 0];
        b_reg_604_pp0_iter1_reg[30 : 0] <= b_reg_604[30 : 0];
        c_reg_78 <= ap_phi_reg_pp0_iter33_c_reg_78;
        c_reg_78_pp0_iter34_reg <= c_reg_78;
        c_reg_78_pp0_iter35_reg <= c_reg_78_pp0_iter34_reg;
        c_reg_78_pp0_iter36_reg <= c_reg_78_pp0_iter35_reg;
        d_reg_638 <= grp_fu_167_p2;
        fpsx_sign_reg_538 <= data_fu_183_p1[32'd31];
        fpsx_sign_reg_538_pp0_iter10_reg <= fpsx_sign_reg_538_pp0_iter9_reg;
        fpsx_sign_reg_538_pp0_iter11_reg <= fpsx_sign_reg_538_pp0_iter10_reg;
        fpsx_sign_reg_538_pp0_iter12_reg <= fpsx_sign_reg_538_pp0_iter11_reg;
        fpsx_sign_reg_538_pp0_iter13_reg <= fpsx_sign_reg_538_pp0_iter12_reg;
        fpsx_sign_reg_538_pp0_iter14_reg <= fpsx_sign_reg_538_pp0_iter13_reg;
        fpsx_sign_reg_538_pp0_iter15_reg <= fpsx_sign_reg_538_pp0_iter14_reg;
        fpsx_sign_reg_538_pp0_iter16_reg <= fpsx_sign_reg_538_pp0_iter15_reg;
        fpsx_sign_reg_538_pp0_iter17_reg <= fpsx_sign_reg_538_pp0_iter16_reg;
        fpsx_sign_reg_538_pp0_iter18_reg <= fpsx_sign_reg_538_pp0_iter17_reg;
        fpsx_sign_reg_538_pp0_iter19_reg <= fpsx_sign_reg_538_pp0_iter18_reg;
        fpsx_sign_reg_538_pp0_iter1_reg <= fpsx_sign_reg_538;
        fpsx_sign_reg_538_pp0_iter20_reg <= fpsx_sign_reg_538_pp0_iter19_reg;
        fpsx_sign_reg_538_pp0_iter21_reg <= fpsx_sign_reg_538_pp0_iter20_reg;
        fpsx_sign_reg_538_pp0_iter22_reg <= fpsx_sign_reg_538_pp0_iter21_reg;
        fpsx_sign_reg_538_pp0_iter23_reg <= fpsx_sign_reg_538_pp0_iter22_reg;
        fpsx_sign_reg_538_pp0_iter24_reg <= fpsx_sign_reg_538_pp0_iter23_reg;
        fpsx_sign_reg_538_pp0_iter25_reg <= fpsx_sign_reg_538_pp0_iter24_reg;
        fpsx_sign_reg_538_pp0_iter26_reg <= fpsx_sign_reg_538_pp0_iter25_reg;
        fpsx_sign_reg_538_pp0_iter27_reg <= fpsx_sign_reg_538_pp0_iter26_reg;
        fpsx_sign_reg_538_pp0_iter28_reg <= fpsx_sign_reg_538_pp0_iter27_reg;
        fpsx_sign_reg_538_pp0_iter29_reg <= fpsx_sign_reg_538_pp0_iter28_reg;
        fpsx_sign_reg_538_pp0_iter2_reg <= fpsx_sign_reg_538_pp0_iter1_reg;
        fpsx_sign_reg_538_pp0_iter30_reg <= fpsx_sign_reg_538_pp0_iter29_reg;
        fpsx_sign_reg_538_pp0_iter31_reg <= fpsx_sign_reg_538_pp0_iter30_reg;
        fpsx_sign_reg_538_pp0_iter32_reg <= fpsx_sign_reg_538_pp0_iter31_reg;
        fpsx_sign_reg_538_pp0_iter33_reg <= fpsx_sign_reg_538_pp0_iter32_reg;
        fpsx_sign_reg_538_pp0_iter34_reg <= fpsx_sign_reg_538_pp0_iter33_reg;
        fpsx_sign_reg_538_pp0_iter35_reg <= fpsx_sign_reg_538_pp0_iter34_reg;
        fpsx_sign_reg_538_pp0_iter36_reg <= fpsx_sign_reg_538_pp0_iter35_reg;
        fpsx_sign_reg_538_pp0_iter3_reg <= fpsx_sign_reg_538_pp0_iter2_reg;
        fpsx_sign_reg_538_pp0_iter4_reg <= fpsx_sign_reg_538_pp0_iter3_reg;
        fpsx_sign_reg_538_pp0_iter5_reg <= fpsx_sign_reg_538_pp0_iter4_reg;
        fpsx_sign_reg_538_pp0_iter6_reg <= fpsx_sign_reg_538_pp0_iter5_reg;
        fpsx_sign_reg_538_pp0_iter7_reg <= fpsx_sign_reg_538_pp0_iter6_reg;
        fpsx_sign_reg_538_pp0_iter8_reg <= fpsx_sign_reg_538_pp0_iter7_reg;
        fpsx_sign_reg_538_pp0_iter9_reg <= fpsx_sign_reg_538_pp0_iter8_reg;
        fpsy_sign_reg_543 <= data_25_fu_209_p1[32'd31];
        fpsy_sign_reg_543_pp0_iter10_reg <= fpsy_sign_reg_543_pp0_iter9_reg;
        fpsy_sign_reg_543_pp0_iter11_reg <= fpsy_sign_reg_543_pp0_iter10_reg;
        fpsy_sign_reg_543_pp0_iter12_reg <= fpsy_sign_reg_543_pp0_iter11_reg;
        fpsy_sign_reg_543_pp0_iter13_reg <= fpsy_sign_reg_543_pp0_iter12_reg;
        fpsy_sign_reg_543_pp0_iter14_reg <= fpsy_sign_reg_543_pp0_iter13_reg;
        fpsy_sign_reg_543_pp0_iter15_reg <= fpsy_sign_reg_543_pp0_iter14_reg;
        fpsy_sign_reg_543_pp0_iter16_reg <= fpsy_sign_reg_543_pp0_iter15_reg;
        fpsy_sign_reg_543_pp0_iter17_reg <= fpsy_sign_reg_543_pp0_iter16_reg;
        fpsy_sign_reg_543_pp0_iter18_reg <= fpsy_sign_reg_543_pp0_iter17_reg;
        fpsy_sign_reg_543_pp0_iter19_reg <= fpsy_sign_reg_543_pp0_iter18_reg;
        fpsy_sign_reg_543_pp0_iter1_reg <= fpsy_sign_reg_543;
        fpsy_sign_reg_543_pp0_iter20_reg <= fpsy_sign_reg_543_pp0_iter19_reg;
        fpsy_sign_reg_543_pp0_iter21_reg <= fpsy_sign_reg_543_pp0_iter20_reg;
        fpsy_sign_reg_543_pp0_iter22_reg <= fpsy_sign_reg_543_pp0_iter21_reg;
        fpsy_sign_reg_543_pp0_iter23_reg <= fpsy_sign_reg_543_pp0_iter22_reg;
        fpsy_sign_reg_543_pp0_iter24_reg <= fpsy_sign_reg_543_pp0_iter23_reg;
        fpsy_sign_reg_543_pp0_iter25_reg <= fpsy_sign_reg_543_pp0_iter24_reg;
        fpsy_sign_reg_543_pp0_iter26_reg <= fpsy_sign_reg_543_pp0_iter25_reg;
        fpsy_sign_reg_543_pp0_iter27_reg <= fpsy_sign_reg_543_pp0_iter26_reg;
        fpsy_sign_reg_543_pp0_iter28_reg <= fpsy_sign_reg_543_pp0_iter27_reg;
        fpsy_sign_reg_543_pp0_iter29_reg <= fpsy_sign_reg_543_pp0_iter28_reg;
        fpsy_sign_reg_543_pp0_iter2_reg <= fpsy_sign_reg_543_pp0_iter1_reg;
        fpsy_sign_reg_543_pp0_iter30_reg <= fpsy_sign_reg_543_pp0_iter29_reg;
        fpsy_sign_reg_543_pp0_iter31_reg <= fpsy_sign_reg_543_pp0_iter30_reg;
        fpsy_sign_reg_543_pp0_iter32_reg <= fpsy_sign_reg_543_pp0_iter31_reg;
        fpsy_sign_reg_543_pp0_iter33_reg <= fpsy_sign_reg_543_pp0_iter32_reg;
        fpsy_sign_reg_543_pp0_iter34_reg <= fpsy_sign_reg_543_pp0_iter33_reg;
        fpsy_sign_reg_543_pp0_iter35_reg <= fpsy_sign_reg_543_pp0_iter34_reg;
        fpsy_sign_reg_543_pp0_iter36_reg <= fpsy_sign_reg_543_pp0_iter35_reg;
        fpsy_sign_reg_543_pp0_iter3_reg <= fpsy_sign_reg_543_pp0_iter2_reg;
        fpsy_sign_reg_543_pp0_iter4_reg <= fpsy_sign_reg_543_pp0_iter3_reg;
        fpsy_sign_reg_543_pp0_iter5_reg <= fpsy_sign_reg_543_pp0_iter4_reg;
        fpsy_sign_reg_543_pp0_iter6_reg <= fpsy_sign_reg_543_pp0_iter5_reg;
        fpsy_sign_reg_543_pp0_iter7_reg <= fpsy_sign_reg_543_pp0_iter6_reg;
        fpsy_sign_reg_543_pp0_iter8_reg <= fpsy_sign_reg_543_pp0_iter7_reg;
        fpsy_sign_reg_543_pp0_iter9_reg <= fpsy_sign_reg_543_pp0_iter8_reg;
        icmp_ln18_1_reg_555 <= icmp_ln18_1_fu_241_p2;
        icmp_ln18_3_reg_564 <= icmp_ln18_3_fu_265_p2;
        icmp_ln715_reg_611 <= icmp_ln715_fu_353_p2;
        icmp_ln715_reg_611_pp0_iter10_reg <= icmp_ln715_reg_611_pp0_iter9_reg;
        icmp_ln715_reg_611_pp0_iter11_reg <= icmp_ln715_reg_611_pp0_iter10_reg;
        icmp_ln715_reg_611_pp0_iter12_reg <= icmp_ln715_reg_611_pp0_iter11_reg;
        icmp_ln715_reg_611_pp0_iter13_reg <= icmp_ln715_reg_611_pp0_iter12_reg;
        icmp_ln715_reg_611_pp0_iter14_reg <= icmp_ln715_reg_611_pp0_iter13_reg;
        icmp_ln715_reg_611_pp0_iter15_reg <= icmp_ln715_reg_611_pp0_iter14_reg;
        icmp_ln715_reg_611_pp0_iter16_reg <= icmp_ln715_reg_611_pp0_iter15_reg;
        icmp_ln715_reg_611_pp0_iter17_reg <= icmp_ln715_reg_611_pp0_iter16_reg;
        icmp_ln715_reg_611_pp0_iter18_reg <= icmp_ln715_reg_611_pp0_iter17_reg;
        icmp_ln715_reg_611_pp0_iter19_reg <= icmp_ln715_reg_611_pp0_iter18_reg;
        icmp_ln715_reg_611_pp0_iter1_reg <= icmp_ln715_reg_611;
        icmp_ln715_reg_611_pp0_iter20_reg <= icmp_ln715_reg_611_pp0_iter19_reg;
        icmp_ln715_reg_611_pp0_iter21_reg <= icmp_ln715_reg_611_pp0_iter20_reg;
        icmp_ln715_reg_611_pp0_iter22_reg <= icmp_ln715_reg_611_pp0_iter21_reg;
        icmp_ln715_reg_611_pp0_iter23_reg <= icmp_ln715_reg_611_pp0_iter22_reg;
        icmp_ln715_reg_611_pp0_iter24_reg <= icmp_ln715_reg_611_pp0_iter23_reg;
        icmp_ln715_reg_611_pp0_iter25_reg <= icmp_ln715_reg_611_pp0_iter24_reg;
        icmp_ln715_reg_611_pp0_iter26_reg <= icmp_ln715_reg_611_pp0_iter25_reg;
        icmp_ln715_reg_611_pp0_iter27_reg <= icmp_ln715_reg_611_pp0_iter26_reg;
        icmp_ln715_reg_611_pp0_iter28_reg <= icmp_ln715_reg_611_pp0_iter27_reg;
        icmp_ln715_reg_611_pp0_iter29_reg <= icmp_ln715_reg_611_pp0_iter28_reg;
        icmp_ln715_reg_611_pp0_iter2_reg <= icmp_ln715_reg_611_pp0_iter1_reg;
        icmp_ln715_reg_611_pp0_iter30_reg <= icmp_ln715_reg_611_pp0_iter29_reg;
        icmp_ln715_reg_611_pp0_iter3_reg <= icmp_ln715_reg_611_pp0_iter2_reg;
        icmp_ln715_reg_611_pp0_iter4_reg <= icmp_ln715_reg_611_pp0_iter3_reg;
        icmp_ln715_reg_611_pp0_iter5_reg <= icmp_ln715_reg_611_pp0_iter4_reg;
        icmp_ln715_reg_611_pp0_iter6_reg <= icmp_ln715_reg_611_pp0_iter5_reg;
        icmp_ln715_reg_611_pp0_iter7_reg <= icmp_ln715_reg_611_pp0_iter6_reg;
        icmp_ln715_reg_611_pp0_iter8_reg <= icmp_ln715_reg_611_pp0_iter7_reg;
        icmp_ln715_reg_611_pp0_iter9_reg <= icmp_ln715_reg_611_pp0_iter8_reg;
        icmp_ln717_1_reg_620 <= icmp_ln717_1_fu_365_p2;
        icmp_ln717_reg_615 <= icmp_ln717_fu_359_p2;
        icmp_ln733_reg_573 <= icmp_ln733_fu_283_p2;
        icmp_ln733_reg_573_pp0_iter10_reg <= icmp_ln733_reg_573_pp0_iter9_reg;
        icmp_ln733_reg_573_pp0_iter11_reg <= icmp_ln733_reg_573_pp0_iter10_reg;
        icmp_ln733_reg_573_pp0_iter12_reg <= icmp_ln733_reg_573_pp0_iter11_reg;
        icmp_ln733_reg_573_pp0_iter13_reg <= icmp_ln733_reg_573_pp0_iter12_reg;
        icmp_ln733_reg_573_pp0_iter14_reg <= icmp_ln733_reg_573_pp0_iter13_reg;
        icmp_ln733_reg_573_pp0_iter15_reg <= icmp_ln733_reg_573_pp0_iter14_reg;
        icmp_ln733_reg_573_pp0_iter16_reg <= icmp_ln733_reg_573_pp0_iter15_reg;
        icmp_ln733_reg_573_pp0_iter17_reg <= icmp_ln733_reg_573_pp0_iter16_reg;
        icmp_ln733_reg_573_pp0_iter18_reg <= icmp_ln733_reg_573_pp0_iter17_reg;
        icmp_ln733_reg_573_pp0_iter19_reg <= icmp_ln733_reg_573_pp0_iter18_reg;
        icmp_ln733_reg_573_pp0_iter1_reg <= icmp_ln733_reg_573;
        icmp_ln733_reg_573_pp0_iter20_reg <= icmp_ln733_reg_573_pp0_iter19_reg;
        icmp_ln733_reg_573_pp0_iter21_reg <= icmp_ln733_reg_573_pp0_iter20_reg;
        icmp_ln733_reg_573_pp0_iter22_reg <= icmp_ln733_reg_573_pp0_iter21_reg;
        icmp_ln733_reg_573_pp0_iter23_reg <= icmp_ln733_reg_573_pp0_iter22_reg;
        icmp_ln733_reg_573_pp0_iter24_reg <= icmp_ln733_reg_573_pp0_iter23_reg;
        icmp_ln733_reg_573_pp0_iter25_reg <= icmp_ln733_reg_573_pp0_iter24_reg;
        icmp_ln733_reg_573_pp0_iter26_reg <= icmp_ln733_reg_573_pp0_iter25_reg;
        icmp_ln733_reg_573_pp0_iter27_reg <= icmp_ln733_reg_573_pp0_iter26_reg;
        icmp_ln733_reg_573_pp0_iter28_reg <= icmp_ln733_reg_573_pp0_iter27_reg;
        icmp_ln733_reg_573_pp0_iter29_reg <= icmp_ln733_reg_573_pp0_iter28_reg;
        icmp_ln733_reg_573_pp0_iter2_reg <= icmp_ln733_reg_573_pp0_iter1_reg;
        icmp_ln733_reg_573_pp0_iter30_reg <= icmp_ln733_reg_573_pp0_iter29_reg;
        icmp_ln733_reg_573_pp0_iter31_reg <= icmp_ln733_reg_573_pp0_iter30_reg;
        icmp_ln733_reg_573_pp0_iter32_reg <= icmp_ln733_reg_573_pp0_iter31_reg;
        icmp_ln733_reg_573_pp0_iter33_reg <= icmp_ln733_reg_573_pp0_iter32_reg;
        icmp_ln733_reg_573_pp0_iter34_reg <= icmp_ln733_reg_573_pp0_iter33_reg;
        icmp_ln733_reg_573_pp0_iter35_reg <= icmp_ln733_reg_573_pp0_iter34_reg;
        icmp_ln733_reg_573_pp0_iter36_reg <= icmp_ln733_reg_573_pp0_iter35_reg;
        icmp_ln733_reg_573_pp0_iter37_reg <= icmp_ln733_reg_573_pp0_iter36_reg;
        icmp_ln733_reg_573_pp0_iter3_reg <= icmp_ln733_reg_573_pp0_iter2_reg;
        icmp_ln733_reg_573_pp0_iter4_reg <= icmp_ln733_reg_573_pp0_iter3_reg;
        icmp_ln733_reg_573_pp0_iter5_reg <= icmp_ln733_reg_573_pp0_iter4_reg;
        icmp_ln733_reg_573_pp0_iter6_reg <= icmp_ln733_reg_573_pp0_iter5_reg;
        icmp_ln733_reg_573_pp0_iter7_reg <= icmp_ln733_reg_573_pp0_iter6_reg;
        icmp_ln733_reg_573_pp0_iter8_reg <= icmp_ln733_reg_573_pp0_iter7_reg;
        icmp_ln733_reg_573_pp0_iter9_reg <= icmp_ln733_reg_573_pp0_iter8_reg;
        icmp_ln737_reg_581 <= icmp_ln737_fu_295_p2;
        icmp_ln737_reg_581_pp0_iter10_reg <= icmp_ln737_reg_581_pp0_iter9_reg;
        icmp_ln737_reg_581_pp0_iter11_reg <= icmp_ln737_reg_581_pp0_iter10_reg;
        icmp_ln737_reg_581_pp0_iter12_reg <= icmp_ln737_reg_581_pp0_iter11_reg;
        icmp_ln737_reg_581_pp0_iter13_reg <= icmp_ln737_reg_581_pp0_iter12_reg;
        icmp_ln737_reg_581_pp0_iter14_reg <= icmp_ln737_reg_581_pp0_iter13_reg;
        icmp_ln737_reg_581_pp0_iter15_reg <= icmp_ln737_reg_581_pp0_iter14_reg;
        icmp_ln737_reg_581_pp0_iter16_reg <= icmp_ln737_reg_581_pp0_iter15_reg;
        icmp_ln737_reg_581_pp0_iter17_reg <= icmp_ln737_reg_581_pp0_iter16_reg;
        icmp_ln737_reg_581_pp0_iter18_reg <= icmp_ln737_reg_581_pp0_iter17_reg;
        icmp_ln737_reg_581_pp0_iter19_reg <= icmp_ln737_reg_581_pp0_iter18_reg;
        icmp_ln737_reg_581_pp0_iter1_reg <= icmp_ln737_reg_581;
        icmp_ln737_reg_581_pp0_iter20_reg <= icmp_ln737_reg_581_pp0_iter19_reg;
        icmp_ln737_reg_581_pp0_iter21_reg <= icmp_ln737_reg_581_pp0_iter20_reg;
        icmp_ln737_reg_581_pp0_iter22_reg <= icmp_ln737_reg_581_pp0_iter21_reg;
        icmp_ln737_reg_581_pp0_iter23_reg <= icmp_ln737_reg_581_pp0_iter22_reg;
        icmp_ln737_reg_581_pp0_iter24_reg <= icmp_ln737_reg_581_pp0_iter23_reg;
        icmp_ln737_reg_581_pp0_iter25_reg <= icmp_ln737_reg_581_pp0_iter24_reg;
        icmp_ln737_reg_581_pp0_iter26_reg <= icmp_ln737_reg_581_pp0_iter25_reg;
        icmp_ln737_reg_581_pp0_iter27_reg <= icmp_ln737_reg_581_pp0_iter26_reg;
        icmp_ln737_reg_581_pp0_iter28_reg <= icmp_ln737_reg_581_pp0_iter27_reg;
        icmp_ln737_reg_581_pp0_iter29_reg <= icmp_ln737_reg_581_pp0_iter28_reg;
        icmp_ln737_reg_581_pp0_iter2_reg <= icmp_ln737_reg_581_pp0_iter1_reg;
        icmp_ln737_reg_581_pp0_iter30_reg <= icmp_ln737_reg_581_pp0_iter29_reg;
        icmp_ln737_reg_581_pp0_iter31_reg <= icmp_ln737_reg_581_pp0_iter30_reg;
        icmp_ln737_reg_581_pp0_iter32_reg <= icmp_ln737_reg_581_pp0_iter31_reg;
        icmp_ln737_reg_581_pp0_iter33_reg <= icmp_ln737_reg_581_pp0_iter32_reg;
        icmp_ln737_reg_581_pp0_iter34_reg <= icmp_ln737_reg_581_pp0_iter33_reg;
        icmp_ln737_reg_581_pp0_iter35_reg <= icmp_ln737_reg_581_pp0_iter34_reg;
        icmp_ln737_reg_581_pp0_iter36_reg <= icmp_ln737_reg_581_pp0_iter35_reg;
        icmp_ln737_reg_581_pp0_iter37_reg <= icmp_ln737_reg_581_pp0_iter36_reg;
        icmp_ln737_reg_581_pp0_iter3_reg <= icmp_ln737_reg_581_pp0_iter2_reg;
        icmp_ln737_reg_581_pp0_iter4_reg <= icmp_ln737_reg_581_pp0_iter3_reg;
        icmp_ln737_reg_581_pp0_iter5_reg <= icmp_ln737_reg_581_pp0_iter4_reg;
        icmp_ln737_reg_581_pp0_iter6_reg <= icmp_ln737_reg_581_pp0_iter5_reg;
        icmp_ln737_reg_581_pp0_iter7_reg <= icmp_ln737_reg_581_pp0_iter6_reg;
        icmp_ln737_reg_581_pp0_iter8_reg <= icmp_ln737_reg_581_pp0_iter7_reg;
        icmp_ln737_reg_581_pp0_iter9_reg <= icmp_ln737_reg_581_pp0_iter8_reg;
        tmp_32_reg_634 <= tmp_32_fu_391_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_pred79_state28 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_pred68_state28 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_177 <= grp_atan2_generic_float_s_fu_156_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_in_int_reg <= x_in;
        y_in_int_reg <= y_in;
    end
end

always @ (*) begin
    if (((tmp_32_reg_634 == 2'd3) & (icmp_ln737_reg_581_pp0_iter37_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter37_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter37_reg) & (1'd0 == and_ln737_reg_585_pp0_iter37_reg) & (1'd0 == and_ln733_reg_577_pp0_iter37_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter37_reg) & (1'd0 == and_ln18_reg_560_pp0_iter37_reg) & (icmp_ln733_reg_573_pp0_iter37_reg == 1'd0))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_104_p40 = bitcast_ln797_1_fu_533_p1;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_104_p40 = ap_phi_reg_pp0_iter38_UnifiedRetVal_reg_92;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp93))) begin
        grp_atan2_generic_float_s_fu_156_ap_ce = 1'b1;
    end else begin
        grp_atan2_generic_float_s_fu_156_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp94) & (ap_predicate_op94_call_state3 == 1'b1))) begin
        grp_atan2_generic_float_s_fu_156_x_in = a_reg_597_pp0_iter1_reg;
    end else if (((ap_predicate_op93_call_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp93))) begin
        grp_atan2_generic_float_s_fu_156_x_in = b_reg_604_pp0_iter1_reg;
    end else begin
        grp_atan2_generic_float_s_fu_156_x_in = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp94) & (ap_predicate_op94_call_state3 == 1'b1))) begin
        grp_atan2_generic_float_s_fu_156_y_in = b_reg_604_pp0_iter1_reg;
    end else if (((ap_predicate_op93_call_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp93))) begin
        grp_atan2_generic_float_s_fu_156_y_in = a_reg_597_pp0_iter1_reg;
    end else begin
        grp_atan2_generic_float_s_fu_156_y_in = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_162_ce = 1'b1;
    end else begin
        grp_fu_162_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_167_ce = 1'b1;
    end else begin
        grp_fu_167_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_173_ce = 1'b1;
    end else begin
        grp_fu_173_ce = 1'b0;
    end
end

assign a_fu_331_p1 = t_31_fu_323_p3;

assign and_ln18_1_fu_277_p2 = (xor_ln18_1_fu_271_p2 & icmp_ln18_2_fu_259_p2);

assign and_ln18_2_fu_307_p2 = (icmp_ln18_3_fu_265_p2 & icmp_ln18_2_fu_259_p2);

assign and_ln18_3_fu_313_p2 = (icmp_ln18_fu_235_p2 & icmp_ln18_1_fu_241_p2);

assign and_ln18_fu_253_p2 = (xor_ln18_fu_247_p2 & icmp_ln18_fu_235_p2);

assign and_ln717_1_fu_385_p2 = (grp_fu_173_p2 & and_ln717_fu_379_p2);

assign and_ln717_fu_379_p2 = (or_ln717_fu_371_p2 & or_ln717_1_fu_375_p2);

assign and_ln733_fu_289_p2 = (icmp_ln733_fu_283_p2 & icmp_ln18_1_fu_241_p2);

assign and_ln737_fu_301_p2 = (icmp_ln737_fu_295_p2 & icmp_ln18_3_fu_265_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp93 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp93 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp94 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1380 = ((icmp_ln715_fu_353_p2 == 1'd1) & (1'd0 == and_ln18_3_fu_313_p2) & (1'd0 == and_ln18_2_fu_307_p2) & (1'd0 == and_ln737_fu_301_p2) & (1'd0 == and_ln733_fu_289_p2) & (1'd0 == and_ln18_1_fu_277_p2) & (1'd0 == and_ln18_fu_253_p2) & (icmp_ln737_fu_295_p2 == 1'd0) & (icmp_ln733_fu_283_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1455 = ((1'd1 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd1 == and_ln18_2_reg_589_pp0_iter36_reg) & (tmp_32_fu_391_p3 == 2'd3) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1460 = ((1'd1 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd1 == and_ln18_2_reg_589_pp0_iter36_reg) & (tmp_32_fu_391_p3 == 2'd2) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1465 = ((1'd1 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd1 == and_ln18_2_reg_589_pp0_iter36_reg) & (tmp_32_fu_391_p3 == 2'd1) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1469 = ((1'd1 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd1 == and_ln18_2_reg_589_pp0_iter36_reg) & (tmp_32_fu_391_p3 == 2'd0) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1476 = ((1'd1 == and_ln18_2_reg_589_pp0_iter36_reg) & (tmp_32_fu_391_p3 == 2'd3) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1479 = ((1'd1 == and_ln18_2_reg_589_pp0_iter36_reg) & (tmp_32_fu_391_p3 == 2'd2) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1482 = ((1'd1 == and_ln18_2_reg_589_pp0_iter36_reg) & (tmp_32_fu_391_p3 == 2'd1) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1485 = ((1'd1 == and_ln18_2_reg_589_pp0_iter36_reg) & (tmp_32_fu_391_p3 == 2'd0) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1512 = ((tmp_32_fu_391_p3 == 2'd1) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter36_reg) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1514 = ((tmp_32_fu_391_p3 == 2'd0) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter36_reg) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1516 = ((tmp_32_fu_391_p3 == 2'd2) & (icmp_ln737_reg_581_pp0_iter36_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter36_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter36_reg) & (1'd0 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (icmp_ln733_reg_573_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1530 = ((1'd1 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (fpsx_sign_reg_538_pp0_iter36_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1533 = ((1'd1 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg) & (fpsx_sign_reg_538_pp0_iter36_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1536 = ((1'd1 == and_ln737_reg_585_pp0_iter36_reg) & (1'd0 == and_ln733_reg_577_pp0_iter36_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter36_reg) & (1'd0 == and_ln18_reg_560_pp0_iter36_reg));
end

assign ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_92 = 'bx;

assign ap_phi_reg_pp0_iter0_c_reg_78 = 'bx;

always @ (*) begin
    ap_predicate_op82_fcmp_state1 = ((icmp_ln715_fu_353_p2 == 1'd0) & (1'd0 == and_ln18_3_fu_313_p2) & (1'd0 == and_ln18_2_fu_307_p2) & (1'd0 == and_ln737_fu_301_p2) & (1'd0 == and_ln733_fu_289_p2) & (1'd0 == and_ln18_1_fu_277_p2) & (1'd0 == and_ln18_fu_253_p2) & (icmp_ln737_fu_295_p2 == 1'd0) & (icmp_ln733_fu_283_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op93_call_state3 = ((icmp_ln715_reg_611_pp0_iter1_reg == 1'd0) & (icmp_ln737_reg_581_pp0_iter1_reg == 1'd0) & (1'd0 == and_ln717_1_reg_625) & (1'd0 == and_ln18_3_reg_593_pp0_iter1_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter1_reg) & (1'd0 == and_ln737_reg_585_pp0_iter1_reg) & (1'd0 == and_ln733_reg_577_pp0_iter1_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter1_reg) & (1'd0 == and_ln18_reg_560_pp0_iter1_reg) & (icmp_ln733_reg_573_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op94_call_state3 = ((1'd1 == and_ln717_1_reg_625) & (icmp_ln715_reg_611_pp0_iter1_reg == 1'd0) & (icmp_ln737_reg_581_pp0_iter1_reg == 1'd0) & (1'd0 == and_ln18_3_reg_593_pp0_iter1_reg) & (1'd0 == and_ln18_2_reg_589_pp0_iter1_reg) & (1'd0 == and_ln737_reg_585_pp0_iter1_reg) & (1'd0 == and_ln733_reg_577_pp0_iter1_reg) & (1'd0 == and_ln18_1_reg_569_pp0_iter1_reg) & (1'd0 == and_ln18_reg_560_pp0_iter1_reg) & (icmp_ln733_reg_573_pp0_iter1_reg == 1'd0));
end

assign ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_104_p40;

assign b_fu_348_p1 = t_32_fu_340_p3;

assign bit_sel1_fu_507_p3 = bitcast_ln797_fu_504_p1[32'd31];

assign bit_sel_fu_401_p3 = bitcast_ln793_fu_397_p1[32'd31];

assign bitcast_ln327_24_fu_489_p1 = t_26_fu_482_p3;

assign bitcast_ln327_25_fu_478_p1 = t_27_fu_471_p3;

assign bitcast_ln327_26_fu_467_p1 = t_28_fu_460_p3;

assign bitcast_ln327_27_fu_456_p1 = t_29_fu_449_p3;

assign bitcast_ln327_28_fu_445_p1 = t_30_fu_438_p3;

assign bitcast_ln327_fu_500_p1 = t_fu_493_p3;

assign bitcast_ln793_1_fu_427_p1 = xor_ln1_fu_419_p3;

assign bitcast_ln793_fu_397_p1 = c_reg_78_pp0_iter36_reg;

assign bitcast_ln797_1_fu_533_p1 = xor_ln_fu_525_p3;

assign bitcast_ln797_fu_504_p1 = d_reg_638;

assign data_25_fu_209_p1 = y_in_int_reg;

assign data_fu_183_p1 = x_in_int_reg;

assign fpsx_exp_fu_195_p4 = {{data_fu_183_p1[30:23]}};

assign fpsx_sig_fu_205_p1 = data_fu_183_p1[22:0];

assign fpsy_exp_fu_221_p4 = {{data_25_fu_209_p1[30:23]}};

assign fpsy_sig_fu_231_p1 = data_25_fu_209_p1[22:0];

assign grp_fu_173_p0 = t_31_fu_323_p3;

assign grp_fu_173_p1 = t_32_fu_340_p3;

assign icmp_ln18_1_fu_241_p2 = ((fpsy_sig_fu_231_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_2_fu_259_p2 = ((fpsx_exp_fu_195_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln18_3_fu_265_p2 = ((fpsx_sig_fu_205_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_235_p2 = ((fpsy_exp_fu_221_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln715_fu_353_p2 = ((t_32_fu_340_p3 == t_31_fu_323_p3) ? 1'b1 : 1'b0);

assign icmp_ln717_1_fu_365_p2 = ((fpsx_exp_fu_195_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln717_fu_359_p2 = ((fpsy_exp_fu_221_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln733_fu_283_p2 = ((fpsy_exp_fu_221_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln737_fu_295_p2 = ((fpsx_exp_fu_195_p4 == 8'd0) ? 1'b1 : 1'b0);

assign or_ln717_1_fu_375_p2 = (icmp_ln717_1_reg_620 | icmp_ln18_3_reg_564);

assign or_ln717_fu_371_p2 = (icmp_ln717_reg_615 | icmp_ln18_1_reg_555);

assign select_ln780_fu_431_p3 = ((fpsy_sign_reg_543_pp0_iter36_reg[0:0] == 1'b1) ? 32'd3217625051 : 32'd1070141403);

assign t_26_fu_482_p3 = {{fpsy_sign_reg_543_pp0_iter36_reg}, {31'd0}};

assign t_27_fu_471_p3 = {{fpsy_sign_reg_543_pp0_iter36_reg}, {31'd1070141403}};

assign t_28_fu_460_p3 = {{fpsy_sign_reg_543_pp0_iter36_reg}, {31'd1078530011}};

assign t_29_fu_449_p3 = {{fpsy_sign_reg_543_pp0_iter36_reg}, {31'd0}};

assign t_30_fu_438_p3 = {{fpsy_sign_reg_543_pp0_iter36_reg}, {31'd1070141403}};

assign t_31_fu_323_p3 = {{1'd0}, {trunc_ln313_fu_319_p1}};

assign t_32_fu_340_p3 = {{1'd0}, {trunc_ln313_24_fu_336_p1}};

assign t_fu_493_p3 = {{fpsy_sign_reg_543_pp0_iter36_reg}, {31'd1078530011}};

assign tmp_32_fu_391_p3 = {{fpsx_sign_reg_538_pp0_iter36_reg}, {fpsy_sign_reg_543_pp0_iter36_reg}};

assign trunc_ln313_24_fu_336_p1 = data_fu_183_p1[30:0];

assign trunc_ln313_fu_319_p1 = data_25_fu_209_p1[30:0];

assign trunc_ln793_fu_415_p1 = bitcast_ln793_fu_397_p1[30:0];

assign trunc_ln797_fu_521_p1 = bitcast_ln797_fu_504_p1[30:0];

assign xor_ln18_1_fu_271_p2 = (icmp_ln18_3_fu_265_p2 ^ 1'd1);

assign xor_ln18_fu_247_p2 = (icmp_ln18_1_fu_241_p2 ^ 1'd1);

assign xor_ln1_fu_419_p3 = {{xor_ln793_fu_409_p2}, {trunc_ln793_fu_415_p1}};

assign xor_ln793_fu_409_p2 = (bit_sel_fu_401_p3 ^ 1'd1);

assign xor_ln797_fu_515_p2 = (bit_sel1_fu_507_p3 ^ 1'd1);

assign xor_ln_fu_525_p3 = {{xor_ln797_fu_515_p2}, {trunc_ln797_fu_521_p1}};

always @ (posedge ap_clk) begin
    a_reg_597[31] <= 1'b0;
    a_reg_597_pp0_iter1_reg[31] <= 1'b0;
    b_reg_604[31] <= 1'b0;
    b_reg_604_pp0_iter1_reg[31] <= 1'b0;
end

endmodule //scatter_matrix_atan2_cordic_float_s
