// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module scatter_matrix_addsub_0_0_ap_fixed_40_1_5_3_0_ap_fixed_40_1_0_3_0_ap_uint_1_s (
        ap_ready,
        a,
        b,
        add,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [39:0] a;
input  [38:0] b;
input  [0:0] add;
output  [39:0] ap_return;
input   ap_rst;

wire   [39:0] zext_ln104_fu_36_p1;
wire   [39:0] add_ln102_fu_46_p2;
wire   [39:0] sub_ln104_fu_40_p2;

assign add_ln102_fu_46_p2 = (zext_ln104_fu_36_p1 + a);

assign ap_ready = 1'b1;

assign sub_ln104_fu_40_p2 = (a - zext_ln104_fu_36_p1);

assign zext_ln104_fu_36_p1 = b;

assign ap_return = ((add[0:0] == 1'b1) ? add_ln102_fu_46_p2 : sub_ln104_fu_40_p2);

endmodule //scatter_matrix_addsub_0_0_ap_fixed_40_1_5_3_0_ap_fixed_40_1_0_3_0_ap_uint_1_s
